### ISSUE TITLE
BGRASVGType bug.

### ISSUE THREAD

**Issue by dimsa** [bgrabitmap/lazpaint#1]
Lazarus Win32. 

If you have svg file with Style Attribute like this:
style="fill:none;fill-rule:evenodd;stroke:#000000;stroke-width:0.73382717px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1"

You got always black, full opaque elements because of
1) When you call for example: 
  val(AttributeOrStyle['fill-opacity'], result, errPos);  

2) In  AttributeOrStyle['fill-opacity'] you got '1.00;' (with semicolon), so, you got non zero error code and default value as the consequence.

Error in
procedure TSVGElement.LocateStyleDeclaration(AText: string; AProperty: string; out AStartPos,
  AColonPos, AValueLength: integer);      

I think AValueLength has wrong value.

Thank you for you lib!

**Comment by lainz** [comment]
Hi,

I've commented this on BGRABitmap forum, you can track your bug status here:
http://forum.lazarus.freepascal.org/index.php/topic,29468.0.html

It was added to SourceForge by circular, the developer of BGRABitmap. This GitHub page is a mirror.

Thanks for sharing this bug. Hopefully it gets fixed soon. Regards.

**Comment by circular17** [comment]
That's fixed in version 9.1 of BGRABitmap
