### ISSUE TITLE
Move layer with keyboard arrow keys

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#102]
Move the image/layer with keyboard arrow is good for an "quick" or "pixel precise" movement.
I guess something like:
1 pixel with arrow keys
10 pixels with shift+arrow
and maybe with any other possible combinations too?
ctrl+arrow
ctrl+shift+arrow
alt+arrow
alt+shift+arrow
and so on...

An example
![arrow-movement](https://i.ibb.co/fCnT6qf/arrow-keys.gif)

**Comment by circular17** [comment]
Yep. That can be added to the move layer tool.

**Comment by circular17** [comment]
Note: align to left / right / top / bottom can be done with menu shortcut

**Comment by circular17** [comment]
Done on dev branch:

1 pixel with arrow keys
1/20 image with ctrl+arrow
align to image border with alt+arrow
