### ISSUE TITLE
Can't open PDN files on MacOS

### ISSUE THREAD

**Issue by panko** [bgrabitmap/lazpaint#104]
Hi all,
i tried to open a pdn file on 10.13.6 osx, and i get an error message:
invalid type cast
from the command line:
$ /Applications/LazPaint.app/Contents/MacOS/lazpaint 237.pdn
TCocoaWidgetSet.GetSystemMetrics TODO 4
TCocoaWidgetSet.GetSystemMetrics TODO 33
TCocoaWidgetSet.GetSystemMetrics TODO 8
TCocoaWidgetSet.GetSystemMetrics TODO 4
TCocoaWidgetSet.GetSystemMetrics TODO 33
TCocoaWidgetSet.GetSystemMetrics TODO 8
$

i could not find any open issues or related documentation, can someone please help me what to do?

**Comment by circular17** [comment]
Hello,
Do you have this error if you open the file from the program?

**Comment by panko** [comment]
Hi, thank you for your reply!

> Do you have this error if you open the file from the program?  

Yeah, when I use the graphical user interface I got this error:
![Screen Shot 2020-01-07 at 18 10 29](https://user-images.githubusercontent.com/1569515/71914334-b1ae1080-3179-11ea-9f9d-23fce4d4739e.png)

> What if you add double quotes "..." around the filename in the command line?  

It's the same:
First:
![Screen Shot 2020-01-07 at 18 22 41](https://user-images.githubusercontent.com/1569515/71914922-ec647880-317a-11ea-8dfd-6259724a4585.png)
Then:
![Screen Shot 2020-01-07 at 18 22 51](https://user-images.githubusercontent.com/1569515/71914939-f6867700-317a-11ea-8dd0-6cbfb2233eb2.png)

**Comment by circular17** [comment]
Ok so clearly it's in the loading of the file. Can you post the PDN file here?

**Comment by circular17** [comment]
Thanks. You can post a zip file. Here I did it for you.
[237.pdn.zip](https://github.com/bgrabitmap/lazpaint/files/4035646/237.pdn.zip)

**Comment by circular17** [comment]
I have the same error here "Invalid type cast" on Linux so I suppose it is not platform specific.

I think it will be easy to fix. Thanks for notifying me.

**Comment by circular17** [comment]
I think it is fixed on dev.

**Comment by circular17** [comment]
Ok I found the problem. It was more likely to happen on MacOS because there was no image browser, but the problem could happen in all versions when loading the image without previewing the it. That's fixed on dev branch.
