### ISSUE TITLE
Multiselection of shapes

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#106]
Recently I did a draw with many forms, as I did so the need arose to take one of these forms, but I wanted to separate it from everything else, without save this form as image (keep form coords) nor hidding the other layers/forms.
So that, as with "save selection" a option to "export/import" form.

Is better if we can select multiple forms too, as with ctrl+click maybe?

Also I wanted change the color from many forms at time, unfortunately I needed make this one by one, so allow make selections from multiple forms can be nice for that too by example.

* Multiple forms selection
* Import/Export form
* Change multiple forms colors at time (well, part of multiple forms selection)

**Comment by circular17** [comment]
I presume that by form you mean shape.

To extract a shape, you can select it and then do Edit>Cut. Then in a new layer, you can paste it. Would that solve your problem?

Regarding export/import, this will be accessible as layers. So by moving some shapes into a layer, you will be able to export it.
https://github.com/bgrabitmap/lazpaint/issues/61

What remains I guess is to have multi-selection of shapes. Is that correct?

**Comment by c-sanchez** [comment]
Ah right, you have reason with Cut/Copy is enough :)
So yes, just remains multi-selection of shapes.

**Comment by lainz** [comment]
The thing is that in Spanish shape is translated sometimes as "forma" and "form" looks closer but isn't the right translation.

**Comment by circular17** [comment]
Done on dev branch and in new beta release
