### ISSUE TITLE
Show info using edit shape tool, improve polygon editor

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#113]
1. The shape coordinates/size is not visible using the edit shape tool.

2. Can be nice also if the point selected with the tool is highlighted in some way to recognize it.
![selected point](https://i.ibb.co/jGjscm5/selected-point.png)
![selected point highlighted](https://i.ibb.co/Phq2kzg/selected-point-highlight.png)

3. Maybe show the coordinates of selected point, and the general form info if selected the entire form, as clicking the red point (form center)?

Forum topic: https://forum.lazarus.freepascal.org/index.php/topic,12037.msg350095.html#msg350095

**Comment by circular17** [comment]
Hmm so that would be highlighting the point hovered with the mouse?

**Comment by c-sanchez** [comment]
I think highlight the selected point better, as there can be two or more points very close together, and the mouse can be on top of several at once.
Maybe I'm asking for too many small details? But, what do you think if you could also move the point selected with the arrows?

**Comment by circular17** [comment]
Hmm, so you suggest to be able to select a point. That's maybe possible. Like the last point that was clicked.

**Comment by circular17** [comment]
>> Maybe I'm asking for too many small details?

Not really. It is rather than I am not exactly sure how to go from how it is now.

**Comment by circular17** [comment]
done showing coordinates in edit shape tool

what remains is improve polygon editor

**Comment by circular17** [comment]
done on dev branch:
- highlighing hovered point
- keys to move hovered point (of one screen pixel or with CTRL of half an image pixel)
![lazpaint_hover_polygon](https://user-images.githubusercontent.com/9092455/75627487-de5a3380-5bd0-11ea-9c45-584e5bfef349.png)

**Comment by c-sanchez** [comment]
hoho that looks very cool! :D
Thanks a billion circular ^^
