### ISSUE TITLE
What is “FilterPlane”

### ISSUE THREAD

**Issue by zirneklitis** [bgrabitmap/lazpaint#124]
Hi.
In  “lazpaintmainform” an object “FilterPlane” is defined. Is it used anywhere?

The corresponding entry in *.po file is:

#: tfmain.filterplane.caption
msgid "Plane (slow)"
msgstr ""

**Comment by circular17** [comment]
It was a filter that would render two opposite planes, similar to perspective transform. I Intended to make it with trilinear filtering, but it was slow. It is hidden for now, I am not sure if I will put it back or not.
