### ISSUE TITLE
Draw opposite plane too does not work in layer context

### ISSUE THREAD

**Issue by zirneklitis** [bgrabitmap/lazpaint#125]
“Draw opposite plane too” do nothing in “Layer perspective” context. (attached video)

.
![Oposit_plane_missing](https://user-images.githubusercontent.com/3538610/76255520-fbd57000-6256-11ea-9784-97aa79a99d7e.gif)

**Comment by circular17** [comment]
Yes it works. The thing is you need to have sufficient perspective and layer repetition to see the second plane:
![two_planes_example](https://user-images.githubusercontent.com/9092455/76309664-81940280-62cd-11ea-8bee-13594d26a6f9.png)
