### ISSUE TITLE
Scroll with Middle Mouse Button out

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#128]
if we scroll with the middle mouse button and release it out of the image edit area, lazpaint continues the scroll until you press the middle mouse button within the edit area.
![lazpaint mmb scroll](https://i.ibb.co/pwVmqjw/lazpaint-mmb-scroll.gif)

**Comment by circular17** [comment]
I don't have the problem on Linux. I have added a fix similar to the one for left and right button, so I suppose it will work. We shall see.
