### ISSUE TITLE
Inner shadow

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#129]
Is possible to add inner shadow?

Is like taking the shape of the object, and using it as a clear mask for the fill color. At least for standard shapes works like that...

Example, the code is at the bgrabitmap/demo repository.
![softui](https://user-images.githubusercontent.com/4131395/76685393-ffb81800-65f1-11ea-9d89-0055cb12f524.PNG)

**Comment by circular17** [comment]
Added inner shadow and inner light script on dev branch.

![test_innershadow](https://user-images.githubusercontent.com/9092455/76689302-dff61380-6634-11ea-8047-8931930d4b17.png)

**Comment by lainz** [comment]
Thanks. I will try it tomorrow.

**Comment by circular17** [comment]
Closing this ticket as it will be part of the layer effects
See https://github.com/bgrabitmap/lazpaint/issues/69

**Comment by lainz** [comment]
Thanks.
