### ISSUE TITLE
.ora: corrupt zip file

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#142]
I saved to .ora format and I get 1kb file, when trying to open it again with LazPaint it fails.

**Comment by circular17** [comment]
Does it happen every time?

I tried to save an Ora file on 32-bit Windows and it seems worked. Would it be on Win64 only?

**Comment by lainz** [comment]
Yes everytime, it says 'unable to create file 00000.tmp'

**Comment by circular17** [comment]
Hmm it seems it's not really that the file is corrupt but that the file is not fully created. Some part of the code seem to use a temporary file and maybe the path that is used is incorrect.

Can you try and debug on your system?

**Comment by lainz** [comment]
I think it writes to the same folder where is the executable, because I executed lazpaint as administrator and it works. By default Program Files where LazPaint is installed is not writable, only with admin permissions.

**Comment by lainz** [comment]
Strange, now it always works, as well without running it as administrator

**Comment by circular17** [comment]
Strange indeed.

Though in any case, it would be better to avoid writing in Program files. Have you found which code creates this temporary file?

**Comment by lainz** [comment]
Is just a guess, I did not found any code on BGRABitmap that matches the '.tmp' extension, on LazPaint there is one match, in the file uimageaction.pas.

So the .tmp creatin is on Lazarus side or FPC...

**Comment by circular17** [comment]
I suppose the filename is generated by `GetTempFilename `function of `SysUtils`.

**Comment by lainz** [comment]
I can't reproduce it anymore, since I opened the application as administrator.

Maybe something with the windows antivirus that didn't allow to create the temporary file for some reason...

**Comment by circular17** [comment]
Ok. I think it may happen if you overwrite the destination file.

**Comment by circular17** [comment]
We'll see if this problem comes up again.
