### ISSUE TITLE
HiDPI on Debian

### ISSUE THREAD

**Issue by neurolabusc** [bgrabitmap/lazpaint#15]
Terrific software! I would like to suggest minor modifications to support high DPI on Debian systems.

On Debian, the function
  ScreenInfo.PixelsPerInchX
always returns 96, regardless of how the user has set the application scaling. The code below can detect the GUI scaling for Debian. Perhaps this could run just once during the initialization of uscaledpi.pas, so Linux systems could use this value if it is not 1.0. It would also be great if we could provide a unified solution on the excellent [High DPI - Lazarus Wiki](http://wiki.lazarus.freepascal.org/High_DPI)

`function getFontScale: single;
var
  AProcess: TProcess;
  Exe: String;
  AStringList: TStringList;
begin
  result := 1.0;
  Exe := FindDefaultExecutablePath('gsettings');
  if length(Exe) < 1 then exit;
  if not FileExists(Exe) then exit;
  AProcess := TProcess.Create(nil);
  AProcess.Executable:=Exe;
  AProcess.Parameters.Add('get');
  AProcess.Parameters.Add('org.gnome.desktop.interface');
  AProcess.Parameters.Add('text-scaling-factor');
  AProcess.Options := AProcess.Options + [poWaitOnExit, poUsePipes];
  AProcess.Execute;
  if (AProcess.ExitCode = 0) then begin
     AStringList := TStringList.Create;
     AStringList.LoadFromStream(AProcess.Output);
     if AStringList.Count > 0 then
        result := strtofloatdef(AStringList.Strings[0], 1.0);
     AStringList.Free;
  end;
  AProcess.Free;
end;
{$ELSE}
function getFontScale: single;
begin
     result := 1.0;
end;
{$ENDIF}`

**Comment by lainz** [comment]
Hi, you I have a question you tested Lazarus 1.7 trunk? They're fixing a lot of stuff regarding High DPI, maybe first you want to tell Lazarus developers in the bugtracker how to properly do High DPI for Debian.

In the future the high dpi stuff should be easy as this:

> Self.AutoAdjustLayout(lapAutoAdjustForDPI, 96, Screen.PixelsPerInch, Self.Width, ScaleX(Self.Width, 96), False);

or if they do it work better, should be like this:

> Set TForm.Scaled=True for all your forms or recompile the LCL with the compiler define LCLScaleForms. All WYSIWYG should work automatically (also the designer). After some time of testing Scaled will be set to True by default and the compiler define changes to LCLDontScaleForms (that sets Scaled=False).

A lot of years ago I created the High DPI wiki, but now is mostly obsolete, because the Lazarus developers are working a lot on High DPI features. So best solve it for all for the next Lazarus 1.8.

**Comment by neurolabusc** [comment]
Thanks for the suggestions.  I have generated a [suggestion](http://mantis.freepascal.org/view.php?id=31199) to update Lazarus to scale forms appropriately. The work in 1.7 looks very promising, and my demo project shows how a tiny modification can handle Ubuntu. As you suggest, we can hope this will soon become something built into the IDE.
