### ISSUE TITLE
Copy aliased doesn't preserve the alpha channel

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#153]
Copying a text aliased or any draw with the pen aliased don't preserve the alpha channel
![copy-aliased-bug](https://i.ibb.co/mJ7CVNQ/alpha-aliased.png)

**Comment by circular17** [comment]
Oh indeed. That's surprising.

**Comment by circular17** [comment]
While checking that I encountered for a moment another bug:
https://github.com/bgrabitmap/lazpaint/issues/155

**Comment by circular17** [comment]
Fixed on dev branch of BGRABitmap
