### ISSUE TITLE
Running Script in Windows 10

### ISSUE THREAD

**Issue by Jairo-Martinez** [bgrabitmap/lazpaint#162]
Hi @circular17 / @lainz 

I am having problems running Scripts in Lazpaint, when I try to execute a option like **Scripts->Layer Effects->Color overlay**, lazpaint always show me:

![Snipaste_2020-05-19_15-32-22](https://user-images.githubusercontent.com/5806694/82375294-fbd7b600-99e5-11ea-8137-8b1052482f23.png)

I was trying to debug Pascal code (I haven't experience with this language) the only thing what I can see is this line in **UPython.pas**

    10: const
    11: DefaultPythonBin = {$IFDEF WINDOWS}'pyw'{$ELSE}'python3'{$ENDIF};

Finally what I need to install or where I need to install? I have versions of Python in C:\Python37 and C:\Python27.

Many thanks.

**Comment by circular17** [comment]
Hello Jairo

It might be that the PATH is not defined or that you don't have `pyw`.

What happens if you write `pyw` from terminal?

**Comment by Jairo-Martinez** [comment]
Thanks @circular17 

    Microsoft Windows [Version 10.0.18363.778]

    Jairo Martinez@DEVJAIROMTZ C:\Users\Jairo Martinez
    $ pyw
    'pyw' is not recognized as an internal or external command,
    operable program or batch file.

Using a full search in Windows I haven't any pyw.exe. If you have the link to download the utility, I'll appreciate. I am googling about pyw.exe now.

Thanks.

**Comment by circular17** [comment]
It is normally part of the installation of Python. Though you could do the following hack.

I am going to suppose that your PATH points to C:\Python37. If you go in this folder, and make a copy of py.exe into pyw.exe, that might work.

The thing is that pyw.exe avoids showing a terminal when running a script, so it is not as pretty.

**Comment by circular17** [comment]
Does your PATH contain either of your Python installations? If I remember correctly, you can display it from the command line by writing `path`.

**Comment by Jairo-Martinez** [comment]
I am reinstalling again Python 3.8, I let you know If after that I can found pyw.exe.

**Comment by circular17** [comment]
Ok. During the process, if it asks whether to install command lines, check it.

**Comment by Jairo-Martinez** [comment]
I selected everything 😄

**Comment by Jairo-Martinez** [comment]
Now is working well.

Many thanks @circular17.
