### ISSUE TITLE
Invalid argument index in format

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#17]
When the image list is empty and you scroll-up an error is shown.
![lazpainterror](https://cloud.githubusercontent.com/assets/4131395/21909936/c6332612-d8f8-11e6-9fd8-144b4c38e16a.PNG)

**Comment by circular17** [comment]
Thanks for reporting.

**Comment by lainz** [comment]
Hi, I will try today

**Comment by lainz** [comment]
Hi, it still happens, I get an exception here:

```
function TVirtualGrid.GetCells(Col, Row: Integer): PCellProps;
begin
  // todo: Check range
  Result:=nil;
  if (Col<0) or (Row<0) or (Col>=ColCount) or (Row>=RowCount) then
    raise EGridException.CreateFmt(rsIndexOutOfRange, [Col, Row]);
  Result:=FCells[Col,Row];
end;
```
Just do View > Image List. Then with no image loaded on that, scroll up and down several times, and then it happens.

**Comment by lainz** [comment]
I see it's a bug on the LCL...

**Comment by circular17** [comment]
Thanks very much now I understand. I have fixed in dev branch of LazPaint by disabling the grid in that case.
