### ISSUE TITLE
Deformation Grid bug

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#178]
The Deformation Grid is buggy.
* It shows an error when you increase the size of the grid and click on it.
* Doesn't instantly change grid size, we must change the tool and select it again to see the change.
* It's slow if we have a "big" grid (?)

A video showing the problems
https://streamable.com/ym57qk

**Comment by circular17** [comment]
Thanks for reporting it

**Comment by circular17** [comment]
fixed on dev branch
