### ISSUE TITLE
Gradient colors and Palette bar

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#179]
If we have a gradient, we can select first and second colors from Colors window, for both pen and back.
But we can't change gradient colors with **palette bar**, if we make left click on the palette bar this will switch to one color (pen) the fill the gradient, if we make right click on the palette bar this will switch to one color fill the gradient (back)

I think is better if possible select even all colors with the palette bar.
A idea could be:

left click to 1st gradient color
right click to 2nd gradient color

alt+left click to 1st gradient color (back)
alt+right click to 2nd gradient color

Video showing the trouble:
https://streamable.com/hnejwe

**Comment by circular17** [comment]
done on dev: Ctrl-Left to select start color, Ctrl-Right to select end color. Applies to selected fill (pen/back/outline).
