### ISSUE TITLE
symmetry tools

### ISSUE THREAD

**Issue by Reaper10** [bgrabitmap/lazpaint#182]
Lazpaint could use symmetry tools, like the one found in krita.
![symmetry tools](https://user-images.githubusercontent.com/8137561/85053370-01006000-b160-11ea-9d9c-4d3e8552d5b2.png)

**Comment by lainz** [comment]
I think is related with this issue
https://github.com/bgrabitmap/lazpaint/issues/94

Not 100% the same, but similar

**Comment by circular17** [comment]
yes it is a duplicate
