### ISSUE TITLE
2048x2048 icon

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#184]
I don't know if it's usefull for something, but I was using Facebook and I've seen that there was a new denoiser for Blender, in fact is the Intel denoiser of the new version, configured in a way that with less samples it produces an high quality image.

So I tried it and I was amazed, with only 32 samples I rendered the LazPaint icon in 2048x2048 size (it used 3200 MB of RAM) and took 5 minutes only.

This is the plugin if you want to try it on your PC
https://www.blendernation.com/2020/04/06/download-super-image-denoiser-node/

I'm not sure, but if I double the resolution again, maybe I'm getting out of RAM so I can not render it at higher resolution like 8K. But 4K looks good enough.

I've uploaded the image into the resources folder, but not updated the blender file because relies in a third party plugin that maybe tomorrow is replaced by something else.

**Comment by lainz** [comment]
Hi, after rendering that and comparing to a render with more samples, seems that the trick is not as good as it sells. I've rendered more complex things and the loss of detail is noticeable.

So when I have time I will render it properly in 2048x2048 with the normal denoiser and a good number of samples, that's more subtle and not too smooth, of course more detailed. I tried to render 4096x4096 and my PC get frozen, so I can't as I was thinking.

See you!

**Comment by circular17** [comment]
Hmm ok.

Well in a way I would prefer not have to big icons anyway as it takes space but it is not really used. 1024x1024 is already pretty big.

But if you would like to experiment, feel free to do so.

**Comment by lainz** [comment]
Ok, I did the 2048 icon, but yes not used for desktops yet, maybe it takes several years to be used, ever decades, I'm stuck with 1920x1080 since a lot of years, so I can understand.

Maybe it's useful for printing, but we need to do our own magazine =)

**Comment by circular17** [comment]
Haha yes indeed printing can have very high resolution!
