### ISSUE TITLE
Error compiling lazpaint-dev

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/lazpaint#186]
Hello.

While compiling last source of lazpaint-dev, with last bgrabitmap-dev, there is that error:

> /lazpaint/./dialog/uchoosecolorinterface.pas(1021,15) Error: (5038) identifier idents no  member "BitmapAutoScale"

It is fixed while commenting line 1021 in uchoosecolorinterface.pas.

`// vsColorView.BitmapAutoScale:= false; // comment this`

**Comment by lainz** [comment]
I don't think is a good idea, I mean before lazpaint was in the same repository with bgrabitmap.

If people don't need bgracontrols and lazpaint why they want to download it with bgrabitmap, I think that is the reason.

In the other hand if you need lazpaint, you need the 3 repositories, thinking in that way yes is a bit more work to download, but not too much.

**Comment by fredvs** [comment]
OK, it makes sense.

Thanks.
