### ISSUE TITLE
Selection lost when copying area multiple times.

### ISSUE THREAD

**Issue by CM630** [bgrabitmap/lazpaint#187]
LazPaint 7.1.3. 64-bit in Win 10

Test case 1:
  Test steps:
    1. Press Ctrl+A (select all).
    2. Press Ctrl+C
    3. Press Ctrl+C 10 times
Expected behaviour:
  Steps 2 and 3: The selected area is copied in the clipboard. The selected area remains unchanged.
Actual behaviour: 
  Step 2: The selected area is copied in the clipboard. The selected area remains unchanged. (OK)
  Step 3: The selected area is copied in the clipboard. The selected area becomes DEselected after several repetitions of Step 3. (NOK)

Test case 2:
  Test steps:
    1. Press Ctrl+A (select all).
    2. Press Ctrl+C
    3. Switch to another Windows application
    4. Switch back to LazPaint
    5. Press Ctrl+C ONCE
Expected behaviour:
  Steps 2 and 5: The selected area is copied in the clipboard. The selected area remains unchanged.
Actual behaviour: 
  Step 2: The selected area is copied in the clipboard. The selected area remains unchanged. (OK)
  Step 3: The selected area is copied in the clipboard. The selected area becomes DEselected (NOK)

**Comment by circular17** [comment]
Thanks I will check that.

**Comment by circular17** [comment]
Test case 1: does it really become deselected or the selection is not highlighted anymore? For example if you click on the tool "Move selection" what happens?

**Comment by circular17** [comment]
Note: I fixed a bug in the render update of the selection.

**Comment by circular17** [comment]
I think it was related to display and is now fixed.
