### ISSUE TITLE
Gradiend in dublicated layers

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#188]
Creating a gradient and duplicating the layer makes them "linked", any change in the gradient made with the edit shape tool is made in all other duplicated layers.
The only way to "unlink" the gradients is making some change like deleting or drawing anything in the layer.

![lazpait image](https://i.ibb.co/BgBvsHR/lazpaint-duplicated-gradient.gif)

It would be fine if the gradient can be edited if you have drawn only with vector tools in this.

**Comment by circular17** [comment]
Yeah, ok so way to unlink the layers, or just not link them.

**Comment by circular17** [comment]
on dev branch: gradient originals are unlinked when duplicated
