### ISSUE TITLE
Adjust Color Curves

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#190]
The window  to adjust color curves have some small bugs.
* The buttons in the top left doesn't have a fixed location.
* Clicking outside the curve box (but inside the window) creates points in the same way.

![adjust color curves](https://i.ibb.co/GRkGsHg/lazpaint-colors.gif)

**Comment by circular17** [comment]
Ohhh indeed.

**Comment by circular17** [comment]
Fixed on dev branch :)
