### ISSUE TITLE
Multishapes selection inside frame

### ISSUE THREAD

**Issue by c-sanchez** [bgrabitmap/lazpaint#191]
Selection multiple shapes makes an "frame" of selection, however, anything inside from this frame can't be selected, so the only solution is try select all desired shapes in an "correct order"

Current way in lazpaint
![lazpaint multiselection](https://i.ibb.co/dG9qqLr/lazpaint-multiselect-shapes.gif)

The same in Illustrator
![ilustrator multiselection](https://i.ibb.co/1dH7DhH/illustrator-multiselect-shapes.gif)

**Comment by circular17** [comment]
Ok I disabled the hitbox of the multi-selection on dev branch. Is it better?

**Comment by c-sanchez** [comment]
Yeah, I guess that's enough :)
