### ISSUE TITLE
Scripting support for JS/TS with Deno

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#192]
This can be interesting:

https://deno.land/manual/getting_started/command_line_interface

It can use the command line like with you do python scripting.
It supports HTML windows as well with a third party plugin, Firefox engine.

With this maybe is possible to give LazPaint JavaScript / TypeScript support.

Is only available for x64.

No need to do this, just a thing I'm learning right now, this can be useful for LazPaint or any of your projects =)

**Comment by circular17** [comment]
Why not in theory. We need more people programming LazPaint I guess. I hope that as it gets more widespread, there would be more incentive for people to come in and participate. That makes me thing of making a post on the Facebook page inviting people to participate.

**Comment by lainz** [comment]
Yes, maybe a group for LazPaint users on Facebook will be good. For example I'm participating on blender and inkscape groups, it can be for developers and non developers. You can do any announcements there.

**Comment by lainz** [comment]
A thing for sure will be having that high standard of code perfectly ordered in classes and inheritance you have done. I'm more of single unit contains all the program ;)

**Comment by circular17** [comment]
I have a tendency as well to put everything in one file or to make big procedures. I have refactored LazPaint code some times already to counter that. Still some things look a bit messy, but well, one thing at a time.

Now I try to put things in classes as soon as possible. To relax and to take some time to think before writing code.

**Comment by lainz** [comment]
Ok. Is hard to think first, some user in the forum has a signature "code first, think later, natural programmer".

About Deno, is a bit "green" (in Spanish mean is a bit immature), so better not to play too much with it, better keep with Python that has several years working well.

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/lazpaint/issues/510

**Comment by circular17** [comment]
See https://github.com/bgrabitmap/lazpaint/issues/553
