### ISSUE TITLE
LazPaint 7.1.4 Win 32 and Win 64.

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/lazpaint#196]
Hello.

This are the binaries I get for last release with fpc 3.2.0, all seems ok here :

Used lazpaint.prj + ideU.

[lazpaint64.exe.zip](https://github.com/bgrabitmap/lazpaint/files/5321792/lazpaint64.exe.zip)
[lazpaint32.exe.zip](https://github.com/bgrabitmap/lazpaint/files/5321793/lazpaint32.exe.zip)

**Comment by circular17** [comment]
Thanks. For people that would like to test that will be useful.

**Comment by circular17** [comment]
Note that as we are testing, it is better to provide the debug versions. They are a bit bigger but show stack trace and display that they are test version in the title, to avoid confusion with actual releases.

**Comment by fredvs** [comment]
OK, here debug version, with -`dDEBUG` and `-gl` compiler options.

> They are a bit bigger

Huh, yes , just a bit (LazPaint.exe 64 bit is 118 megas, 28 megas zipped...).
Sorry but GitHub do not allow to upload big files (> 25 megas), so I can only upload the win 32 debug version.

[lazpaint_win32.exe.zip](https://github.com/bgrabitmap/lazpaint/files/5321851/lazpaint_win32.exe.zip)

**Comment by lainz** [comment]
Maybe uploading them in a pre-release tag?

Google drive.. Dropbox, etc.

**Comment by fredvs** [comment]
Hello.

Here the LazPaint.exe debug 64 bit compressed with tar.xz, it is only 16 megas.
But I was obliged to rename it to tar.xz.zip because github dont accept tar.xz files.
So once downloaded, remove the .zip extension.

[lazpaint_win64_debug.exe.tar.xz.zip](https://github.com/bgrabitmap/lazpaint/files/5321889/lazpaint_win64_debug.exe.tar.xz.zip)

**Comment by fredvs** [comment]
> Maybe uploading them in a pre-release tag?

Ho, yes that is a good idea.
Maybe first test here then move it to pre-release.

**Comment by circular17** [comment]
Yeah I will publish as prerelease soon, just trying to fix most obvious bugs first.
