### ISSUE TITLE
Updating BgraUtf8.pas

### ISSUE THREAD

**Issue by abtaylr** [bgrabitmap/lazpaint#2]
I have updated BgraUtf8.pas to clear the deprecated messages dealing with methods that make use of FileUtil.pas and LCLProc.pp. The Lazarus 1.5/FPC 3.0+ version have added significantly to the use of UNICODE, UTF8, UTF16 support thoughout the units.  The result is that the existing file BgraUtf8.pas creates warnings concerning deprecated methods.  My effort has been to make changes to the preferred methods found in LazUTF8 and LazFileUtils.

**Comment by abtaylr** [comment]
I have created a patch, but I am not sure how to upload it . . .

**Comment by circular17** [comment]
Fixed in last version of BGRABitmap
