### ISSUE TITLE
Set value by scrolling over input field

### ISSUE THREAD

**Issue by Krypton-Nova** [bgrabitmap/lazpaint#205]
It's just a minor quality-of-life improvement, but perhaps it would be intuitive if input fields which can be linearly incremented or decremented (such as width, light, opacity, etc.) would respond to scrolling when selected and/or hovered over, to be able to quickly change it? Other applications like Krita, Gimp and Paint.NET do this too.

As a side note, I'm using LazPaint on Linux Mint 20 and really liking it :)

![image](https://user-images.githubusercontent.com/38065396/96364872-2ec0da00-113d-11eb-8477-f7868627aad8.png)

**Comment by circular17** [comment]
Hello,

I am glad you like my software.

What do you mean by scrolling?

**Comment by lainz** [comment]
I think it means mouse wheel.

**Comment by Krypton-Nova** [comment]
Yes, I mean using the mouse wheel to change the value :)

**Comment by circular17** [comment]
done on dev branch
