### ISSUE TITLE
Simplify gradient usage

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#207]
- when choosing gradient tool, select the background color in the color window
- to be able to paste with Ctrl-V when the text box of the color definition is active (and also always Ctrl-C), needs to deactivate text box when clicking anywhere else.
- to select the pen/back color in the color window when using the color picker (so that one necessarily see its definition without having to select it in the top toolbar)

**Comment by circular17** [comment]
done on dev

**Comment by lainz** [comment]
I need to test this just remember me on sunday.

**Comment by circular17** [comment]
Ok

**Comment by circular17** [comment]
How to test:
1
- select the Pen color by clicking on its preview in the top toolbar. In the color chooser, it should display "Pen"
- select the Gradient tool. In the color chooser, it should now display "Back[1]" without having to click on the top preview.

2
- in the color chooser, select the text definition of the color. Do Ctrl-C to copy.
- Then choose another color instead, which would change the definition.
- Go in the text definition and do Ctrl-V to put back the previous definition.

3
- using the color picker on an image, do left-click, that will set the pen color and in the color chooser display "Pen"
- now do right-click, that will set back color and in the color chooser display "Back"

**Comment by lainz** [comment]
1) Ok, works fine.
2) Ok, works fine.
3) Ok, works fine.
