### ISSUE TITLE
ComboBox below window

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#208]
As you can see in the screenshot, the combobox is below the layer window. LazPaint 7.1.5
![Captura de pantalla 2020-10-25 071841](https://user-images.githubusercontent.com/4131395/97104404-632f1b80-1692-11eb-96db-4c614162860a.png)

**Comment by fredvs** [comment]
The same here on Linux 64 bit:

![Capture d’écran_2020-10-25_12-18-28](https://user-images.githubusercontent.com/3421249/97105608-735bf080-16bc-11eb-9070-887c47fbbb73.png)

**Comment by circular17** [comment]
Hmm ok, maybe it is not fsStayOnTop or something.

**Comment by circular17** [comment]
fixed on dev-bgracontrols branch
