### ISSUE TITLE
FreeBSD and ARM RPi binary release of LazPaint 7.1.5

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/lazpaint#209]
Hello everybody.

I am back near my machines.

What code should I use for producing the LazPaint 7.1.5 release?

The one from trunk or main or a other?

Fre;D.

**Comment by circular17** [comment]
Hi Fred,

Basically as it is the latest release, you can use the releases of lazpaint and its libraries. Those are basically the master branches.

Regards

**Comment by fredvs** [comment]
Hello and sorry for the delay.

I try to compile Lazpaint using last commit of lazpaint-master, bgrabitmap-master and bgracontrols-master.
FPC 3.2.0 is used and code of last (maybe?) Lazarus source.

But there is a error at compilation:

```
/home/fred/lazpaint-master/lazpaintcontrols/lcvectororiginal.pas(442,14):
Error: (3058) There is no method in an ancestor class to be overridden: "ConvertToSVG(const TAffineMatrix;out TPoint):TObject;

/home/fred/lazpaint-master/lazpaintcontrols/lcvectororiginal.pas(478,20):
 Error: (3058) There is no method in an ancestor class to be overridden: "class CanConvertToSVG:Boolean;

/home/fred/lazpaint-master/lazpaintcontrols/lcvectororiginal.pas(523,1):
 Fatal: (10026) There were 2 errors compiling module, stoppingFatal: (1018) Compilation aborted
```
What do I miss?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Ooops, ok, it compiles now, sorry for the noise.

Did you change the resource of that new release (lazpaint.res)?
(Because I have still problems to create lazpaint.res and so I did use the one of previous release).

If you did change it, no problem, I will first compile it with Lazarus-Windows and use that lazpaint.res.

**Comment by fredvs** [comment]
Note that, in **lazpaint.lpr** at line 155:

Changing this:

`{$R *.res}`

With this:

`{$R *.rc}`

Make compilation with fpc 3.2.0 ok and resource is included too (it seems fpc uses now fpcres for Linux and no more windres):

```
(9022) Compiling resource /home/fred/lazpaint-master/lazpaint/lazpaint.rc
(9022) Compiling resource units/lazpaint.or
```

**Comment by circular17** [comment]
Hi

There is a RES file for you in the resources directory

**Comment by fredvs** [comment]
> There is a RES file for you in the resources directory

Not for me:

https://github.com/bgrabitmap/lazpaint/tree/master/resources

;-(

**Comment by fredvs** [comment]
> Also you can use the lazpaint-upstream repository

Hum, ok, but is it synchro with lazpaint-master, it seems that some commits where done?

**Comment by circular17** [comment]
> > There is a RES file for you in the resources directory
> 
> Not for me:
> 
> https://github.com/bgrabitmap/lazpaint/tree/master/resources
> 
> ;-(

Look there:
https://github.com/bgrabitmap/lazpaint-upstream/tree/master/resources

> > Also you can use the lazpaint-upstream repository
> 
> Hum, ok, but is it synchro with lazpaint-master, it seems that some commits where done?

Yeah, if there was a new version, there would be a new number etc.

Though something to check is that there is no error when you do Render > Water or something from that menu. That is related to a compiler error and is easy to fix.

**Comment by fredvs** [comment]
OK.

**Comment by fredvs** [comment]
>   Also you can use the lazpaint-upstream repository
>>  Hum, ok, but is it synchro with lazpaint-master, it seems that some commits where done?
>>> Yeah, if there was a new version, there would be a new number etc.

I did try to compile lazpaint from lazpaint-upstream but there are lot of error about uxxx.pas files.

**Comment by fredvs** [comment]
Hello.

Included LazPaint version 7.1.6  for FreeBSD 64 bit.

Note that _cmem_ was added as first unit in _lazpaint.lpr_ uses section otherwise the application crashed for each action.

Also optimization needed to be set as -O1.

![lazpaint7 1 6_FreeBSD64](https://user-images.githubusercontent.com/3421249/102415649-d7ce6880-3ff8-11eb-8ecc-f8f6611bc810.png)

[lazpaint7.1.6_freebsd64_no_install.tar.gz](https://github.com/bgrabitmap/lazpaint/files/5705865/lazpaint7.1.6_freebsd64_no_install.tar.gz)

PS: Release for Rpi comes asap (have problems with hdmi screen).

**Comment by circular17** [comment]
> I did try to compile lazpaint from lazpaint-upstream but there are lot of error about uxxx.pas files.

Missing files?

> Included release of LazPaint version 7.1.6 for FreeBSD 64 bit.
> 
> Note that _cmem_ was added as first unit in _lazpaint.lpr_ uses section otherwise the application crashed for each action.
> 
> Also optimization needed to be set as -O1.

Ok. Thank you very much indeed.

> PS: Release for Rpi comes asap (have problems with hdmi screen).

Alright

**Comment by fredvs** [comment]
> did try to compile lazpaint from lazpaint-upstream but there are lot of error about uxxx.pas files.
>> Missing files?

No, methods that do not have same parameters as declared, different format of parameters, ...
Bref, some (lot of) _uxxx.pas_ files that are in _lazpaint-upstream_ and are not the same that those used with _lazpaint-master_

So, to make it simpler, I did use the code of _lazpaint-master_ , _brabitmap-master_ and _bgracontrol-master_.

**Comment by circular17** [comment]
Alright, whatever feels more comfortable

**Comment by fredvs** [comment]
Hello.

Included release of LazPaint version 7.1.6 for ArmRPi 32 bit.

I did not yet the Debian version, I have to remember how to do (or maybe there is a how-to ?).

![lazpaint7_1_6_armRPi32](https://user-images.githubusercontent.com/3421249/102533366-9f389880-40a5-11eb-919b-26896f154307.png)

[lazpaint7.1.6_arm-rpi32_no_install.tar.gz](https://github.com/bgrabitmap/lazpaint/files/5711679/lazpaint7.1.6_arm-rpi32_no_install.tar.gz)

**Comment by circular17** [comment]
Thanks Fred you rock

About the Deb, normally you can do it with the makedeb script:
https://github.com/bgrabitmap/lazpaint/tree/master/lazpaint/release/debian

**Comment by fredvs** [comment]
> About the Deb, normally you can do it with the makedeb script:

Ha, ok, I will try.

Hum, about the assert of lazpaint7.1.6_arm-rpi32_no_install.tar.gz and Raspbian...

They change the name of Raspbian to Raspberry-pi-OS.

https://unix.stackexchange.com/questions/602587/why-has-raspbian-apparently-been-renamed-into-raspberry-pi-os

PS: Not very important, only for the "purists".

**Comment by fredvs** [comment]
> About the Deb, normally you can do it with the makedeb script:

Ha, this one was really OOTB, well done Circular.

Also installed the _deb_ and all was ok, nice.

Included the binaries produced by _makedeb_ script (._deb_ and _no_install_) and a screenshot.

Note that Github dont allow to upload _.deb_ files, so _lazpaint7.1.6_armhf.deb_ was renamed into _lazpaint7.1.6_armhf.deb_**.zip**. After downloading it, just remove the ".zip" extension.

![lazpaint716_rpi_deb](https://user-images.githubusercontent.com/3421249/102627786-0196a500-4149-11eb-8d3a-2a3ca0847351.png)

[lazpaint7.1.6_armhf_no_install.tar.gz](https://github.com/bgrabitmap/lazpaint/files/5716373/lazpaint7.1.6_armhf_no_install.tar.gz)

[lazpaint7.1.6_armhf.deb.zip](https://github.com/bgrabitmap/lazpaint/files/5716376/lazpaint7.1.6_armhf.deb.zip)

**Comment by circular17** [comment]
Thanks. I am not sure, but those are raspbian 64 basically, so different from raspbian 32?

**Comment by fredvs** [comment]
Or maybe I did not catch.

Indeed even Rpi 2 processor is 64 bit but when installing last release of Raspberry OS, It install a 32 bit release.

I have to study how to install the 64 bit OS.

**Comment by fredvs** [comment]
Ha, ok, I will try to install RPi OS 64 bit.

https://qengineering.eu/install-raspberry-64-os.html

Asap.

**Comment by fredvs** [comment]
Hello everybody.

About Raspberry Pi OS 64 bit.

OK, I was able to install it on a Rpi 3 machine.
But...
It is highly unstable, if you do a apt-get update, after the Rpi does not reboot.

Also many installed applications crash after few time and are much slower that the 32 bit equivalent.

I was able to install fpc for aarch64.
But...

Only simple console application are working (application that uses threads crash).
For GUI application, I was able to compile simple fpGUI and MSEgui applications, but only with 1 main thread.

For Lazarus, like for the Raspberry OS 32 bit, I was not able to compile it and install it on Rpi OS 64 bit.
(If I was able to compile lazpaint for Rpi 32 bit, it is because I used ideU or command line.)

So I have very sad news, I give it up at the moment for Rpi OS 64 bit.
It is very rare that I take such a decision, I am a explorer_warrior after all.
But in that case I have to be realist, Rpi OS 64 bit and fpc aarch64 are too unstable for the moment.

All that said, if people was able to compile+run lcl or fpGUI or MSEgui big applications on Rpi OS 64 bit, I am more than interested to know how to do and what to change.

Fre;D

**Comment by fredvs** [comment]
Hello everybody.

About Raspberry Pi OS 64 bit.

OK, I was able to install it on a Rpi 3 machine.
But...
It is highly unstable, if you do a apt-get update, after the Rpi does not reboot.

Also many installed applications crash after few time and are much slower that the 32 bit equivalent.

I was able to install fpc for aarch64.
But...

Only simple console application are working (application that uses threads crash).
For GUI application, I was able to compile simple fpGUI and MSEgui applications, but only with 1 main thread.

For Lazarus, like for the Raspberry OS 32 bit, I was not able to compile it and install it on Rpi OS 64 bit.
(If I was able to compile lazpaint for Rpi 32 bit, it is because I used ideU or command line.)

So I have very sad news, I give it up at the moment for Rpi OS 64 bit.
It is very rare that I take such a decision, I am a explorer_warrior after all.
But in that case I have to be realist, Rpi OS 64 bit and fpc aarch64 are too unstable for the moment.

All that said, if people was able to compile+run lcl or fpGUI or MSEgui big applications on Rpi OS 64 bit, I am more than interested to know how to do and what to change.

Fre;D

OK, I was able to install it on a Rpi 3 machine.
But...
It is highly unstable, if you do a apt-get update, after the Rpi does not reboot.

Also many installed applications crash after few time and are much slower that the 32 bit equivalent.

I was able to install fpc for aarch64.
But...

Only simple console application are working (application that uses threads crash).
For GUI application, I was able to compile simple fpGUI and MSEgui applications, but only with 1 main thread.

For Lazarus, like for the Raspberry OS 32 bit, I was not able to compile it and install it on Rpi OS 64 bit.
(If I was able to compile lazpaint for Rpi 32 bit, it is because I used ideU or command line.)

So I have very sad news, I give it up at the moment for Rpi OS 64 bit.
It is very rare that I take such a decision, I am a explorer_warrior after all.
But in that case I have to be realist, Rpi OS 64 bit and fpc aarch64 are too unstable for the moment.

All that said, if people was able to compile+run lcl or fpGUI or MSEgui big applications on Rpi OS 64 bit, I am more than interested to know how to do and what to change.

Fre;D

**Comment by fredvs** [comment]
Hello.

Ok I went back to exploration:

Finally I was able to install Rpi OS aarch64 more or less stable.
FPC runs ok, msegui applications can be compiled and run nicely.

Now about Lazpaint and LCL on aarch64-linux.

I have a coñpilation error at controls.pas. 

/home/pi/lazarus/lcl/controls.pas(1186,17) Error: (5000) Identifier not found "TPopupMenu"
/home/pi/lazarus/lcl/controls.pas(1186,27) Error: (5007) Error in type definition
/home/pi/lazarus/lcl/controls.pas(1267,45) Error: (5000) Identifier not found "TPopupMenu"
/home/pi/lazarus/lcl/controls.pas(1454,38) Error: (5000) Identifier not found "TPopupMenu"
/home/pi/lazarus/lcl/controls.pas(1731,36) Error: (5000) Identifier not found "TPopupmenu"
/home/pi/lazarus/lcl/controls.pas(2791,1) Fatal: (10026) There were 5 errors compiling module, stopping
Fatal: (1018) Compilation aborted
Error: /usr/bin/ppca64 returned an error exitcode

I really dont understand why because I checked source and in uses section "menus" is there.

Do you have a idea why Identifier not found "TPopupMenu" ?

I did try with source of lazarus 2.10 and trunk but same error.

Ho, yes, Happy New Year y Feliz Navidad et Joyeuses Fêtes and more.

Fre;D

**Comment by fredvs** [comment]
Toc, toc, toc, yakelkun ?

>  Identifier not found "TPopupMenu"

No idea?

**Comment by circular17** [comment]
Personally I have no idea.

**Comment by fredvs** [comment]
Allez, time to finish the year in beauté:

![lazpaint_aarch64](https://user-images.githubusercontent.com/3421249/103161296-de6e9400-47df-11eb-904f-7a43dfa8a9cf.png)

Here the working compiled LazPaint for aarch64-linux, deb and no_install.
Dont forget to remove the ".zip" extension of the deb file (due to github limitation)

[lazpaint7.1.6_aarch64.deb.zip](https://github.com/bgrabitmap/lazpaint/files/5743913/lazpaint7.1.6_aarch64.deb.zip)

[lazpaint7.1.6_aarch64_no_install.tar.gz](https://github.com/bgrabitmap/lazpaint/files/5743914/lazpaint7.1.6_aarch64_no_install.tar.gz)

Fre;D

**Comment by circular17** [comment]
Ohh congrats! Thanks
