### ISSUE TITLE
LazPaint cannot save much colored pic as BMP 256 colors

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#21]
After some editing I have too much colors in pic (i didnt want it),
and now I cannot save pic as BMP 16 color or 256 color. It allows only 24bit.
Pls, ALWAYS enable them, so I can save pic with downsample to 256 colors.

**Comment by circular17** [comment]
That works in current development version. When you modify the image, you add more colors to it, and when you save, you can select back 4bits or 8bits per pixel if you wish. Note that this is possible only if there are not transparent pixels. You may need to add a background layer to make sure to fill every pixel as only BMP 32bit and BMP MioMap can handle transparency.

**Comment by Alexey-T** [comment]
Good, thanks
