### ISSUE TITLE
Copying an image from Firefox fails

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#210]
Hi,
if you copy an image from Firefox (last version: 82.0.2 Windows 64bit) using the contextual menu ("Copy image") and then paste it in Lazpaint (menu Edit, any of the three past commands) you will get a "Unexpected response status code: 301" error and then an AV message.
If you copy the same image from Chrome, it works fine.
If you copy the image from Firefox to MS Paint and then from Paint to Lazpaint, it works fine.
Thanks for your support,
Domenico

from: https://sourceforge.net/p/lazpaint/bugs/39/

**Comment by circular17** [comment]
Hello Demonico,

The error 301 means the content was moved to another URL. Do you always get this error or is it specific to some website or image?

**Comment by lainz** [comment]
I can't reproduce this bug. There are corner cases with images, maybe he was using google search and these images are just cache or inlined.

**Comment by lainz** [comment]
Indeed, copying an image from google image search thumbnails causes an access violation.

**Comment by circular17** [comment]
Ah yeah, google adds redirections. That will help me reproduce the bug.

**Comment by circular17** [comment]
Well this doesn't happen on MacOS.

**Comment by lainz** [comment]
I think the data is base64, but I guess that is a different bug-

**Comment by lainz** [comment]
With Chrome works, but with Firefox on Windows it gives an error, invalid 'data'
https://jsfiddle.net/casiano/Xadvz/

**Comment by lainz** [comment]
https://jsfiddle.net/casiano/Xadvz/
![image](https://user-images.githubusercontent.com/4131395/98477710-412ab280-21d5-11eb-9a92-4ac0579630f6.png)

**Comment by circular17** [comment]
Ok that's yet another case.

**Comment by circular17** [comment]
fixed both issues on dev
