### ISSUE TITLE
Dark theme question

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#238]
I'm using a dark theme in the system. When I disable dark theme in the menu, it looks lighter but the hover drawing is not updated accordingly, it remains "dark darker" (check on this image the zoom in button in the top toolbar).
![VirtualBox_Debian_12_12_2020_22_41_45](https://user-images.githubusercontent.com/4131395/102000962-52327c00-3ccb-11eb-84cd-bfd282d68035.png)

**Comment by lainz** [comment]
Also if I disable dark theme, the setting is ignored the next time I open the application.

**Comment by lainz** [comment]
Mmm as I understand it now seems that's a feature not a bug.

Since there is no default "dark theme" colors for windows and linux, it needs to paint the button hover as well with the toolbar event, so for that is not disabled using the OS default.

And about the second comment, I think you said it works like that, so it uses always dark darker if the theme of the OS is dark.

If all is ok please close this bug =)

**Comment by circular17** [comment]
It is indeed one little thing that can be improved.

**Comment by circular17** [comment]
fixed on dev
