### ISSUE TITLE
Can't load this SVG

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#239]
Hi, seems that I can't load this SVG with LazPaint
https://lainz.github.io/logo.svg

It looks like this on Debian and Windows
![Captura de pantalla 2020-12-13 065059](https://user-images.githubusercontent.com/4131395/102008483-acedc700-3d0f-11eb-8d12-e1689a2a6577.png)

I made that SVG with Corel Draw not with Inkscape, so maybe there is a clue or something with that. It uses a Corel Draw feature called power clip, you can check on this video
https://www.youtube.com/watch?v=GwGBQptl9EA

I think this bug can have low priority, I was just playing with the program to see, I'm not using that image in a real program or editing it right now

**Comment by circular17** [comment]
Ok, it is an interesting case of using clipPath and multiple CSS classes.

**Comment by circular17** [comment]
done in dev
