### ISSUE TITLE
lazarus 1.8.4 +win10+64bit,build failed

### ISSUE THREAD

**Issue by waleson** [bgrabitmap/lazpaint#24]
env:  lazarus 1.8.4 +win10+64bit

there are lots of error:  

1. Error: Found declaration: SysToUTF8 , SysToUTF16,FileExistUTF8

after add the uses : LAZUtils, LazUTF8,LazFileUtils, to the error units,  it seems ok,

2. the math round() function in uadjustcurves.pas confict with the types.pp  
Error: Found declaration: Round:<record type>;--

so, I changed the round() to ceil(), it finally worked.

3. LCLGetLanguageIDs(）not found
   utranslation.pas(79,3) Error: Identifier not found "LCLGetLanguageIDs"
   
so I commented(disabled) it with //LCLGetLanguageIDs()

Finally, it worked.

**Comment by waleson** [comment]
and LCLGetLanguageIDs（）not found
utranslation.pas(79,3) Error: Identifier not found "LCLGetLanguageIDs"

**Comment by circular17** [comment]
Hi! There has been a lot of changes lately in the LCL. The current version of LazPaint compiles with Lazarus 1.6. On the other hand, the dev-lazpaint branch contains an experimental version that can be compiled with latest version of LCL. It probably contains all the fixes you're mentionning.
