### ISSUE TITLE
Realloc error on opening large image

### ISSUE THREAD

**Issue by Shkarlatov** [bgrabitmap/lazpaint#244]
When i open very large image I get error:  TBGRAWinBitmap.ReallocBitmap: Windows error 87
Image properties: (opened in IrfanView)
![Clipboard01](https://user-images.githubusercontent.com/1247023/108027126-16a58c80-7043-11eb-98d6-d5c4adb688c9.jpg)

LazPaing 7.1.6 (64-bit) 
Win 10 Pro x64 (19042.804)

**Comment by circular17** [comment]
Yep, that's kind of expected.
