### ISSUE TITLE
Problem with the width of dialog boxes on Linux (fixed on MacOS)

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#249]
All dialog boxes increase in width after each opening. Notice how the selector gradually approaches the right edge of the screen. The window width cannot be changed manually.
The complete removal of the program with all the settings didn't solve this problem, after re-installing LazPaint the dialog box continued to expand from the previous size.
It is not necessary to save the file, just open and close the dialog box.

This behavior is common for "Open", "Import layer from file", "Save as", "Export", "Run script", etc.

MacOS 11.5.2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/15073200/131957430-aa27e670-cd0a-4c14-afc0-df492767ed25.mp4

Same problem on Ubuntu 20.04.2.
The open file dialog box:
![open](https://user-images.githubusercontent.com/15073200/131958314-5df93828-89bf-4576-8af3-1b338c2ad2fd.png)

The save file dialog box:
![save](https://user-images.githubusercontent.com/15073200/131958337-d85c213a-cc6b-49ff-8328-7929cc3e7c65.png)

The open file dialog box has crossed the screen limits.
The save file dialog box and other dialog boxes was limited by the size of the screen.

**Comment by circular17** [comment]
Hmmm looks like a big in the LCL, thanks for reporting it

**Comment by circular17** [comment]
It seems it is fixed in the LCL

**Comment by circular17** [comment]
Remain to check if fixed on Linux

**Comment by circular17** [comment]
Fixed on Linux as well.
