### ISSUE TITLE
Compiling on macOS

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#25]
Hi, I finally have the Mac. BGRABitmap, BGRAControls, MaterialDesign, all compiled fine.

When I try to compile LazPaint the first problem I found is this:
`    if (Clipboard.Formats[i] = PredefinedClipboardFormat(pcfDelphiBitmap)) or `

In the clipboard unit.

Maybe you want to install Lazarus trunk on Linux to test as well, is a change on the LCLType unit.

I'm using fpcupdeluxe to install, nothing else works on Mac, but Lazarus trunk and FPC trunk 64 bit.

**Comment by circular17** [comment]
Cool.

What is the error message from the compiler?

**Comment by circular17** [comment]
Ok, I removed the line on the dev branch. Is there anything else that prevents compiling?

**Comment by circular17** [comment]
By the way I tidied up a bit the clipboard unit as Tiff format is supported without having to define the reader/writer.

**Comment by circular17** [comment]
Note : my current Lazarus is from fpcup, it is version 1.8.0 with fpc 3.0.4.

**Comment by lainz** [comment]
Hi, I will test it again.

**Comment by lainz** [comment]
It compiles now, but it starts and then closes. But that's for another issue, I need to see how to debug (if possible with a really broken IDE) on Mac. So this part of compiling is solved.
