### ISSUE TITLE
Unexpected behavior of the toolbox display

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#250]
If I turn off the toolbox display and open the program again, it will be displayed again. A couple of times it turned out the opposite: the toolbar is turned off, I activate its display, but after reopening it disappears.
Doesn't matter, how to do this: uncheck in the menu, press `⌘+T` or press F6.
Switching the display of all other elements works fine.

This is common for MacOS 11.5.2, Windows 10 (21H1 19043.1083), Ubuntu 20.04.2.
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/15073200/131959475-a24fbb14-2ac8-4f9d-aecf-5434fccb3f76.mp4

**Comment by circular17** [comment]
fixed on dev
