### ISSUE TITLE
A hotkey conflict in MacOS

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#251]
In MacOS the same hotkey is assigned for two operations.
`⌘+H` on Mac is used to hide the current window, but in LazPaint it is a hotkey for Horizontal Flip. When I pressed this hotkey to hide LazPaint, I didn't notice that the Horizontal Flip action had occurred. Nothing happened for me.

MacOS 11.5.2
LazPaint 7.1.6 (64-bit)

![Screenshot 09-03-2021 13 34 00](https://user-images.githubusercontent.com/15073200/131961378-e368402a-da5a-432f-8abe-f7ee0c272b8f.png)
![Screenshot 09-03-2021 13 34 06](https://user-images.githubusercontent.com/15073200/131961382-b4bc38a0-5e30-42c4-84a6-763e39c2c9d5.png)

**Comment by circular17** [comment]
fixed on dev
