### ISSUE TITLE
The disappearance of the submenu in the toolbox in MacOS

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#252]
When you hover the cursor over some toolbox elements, the submenu appears. If you open any dialog box (it does not matter whether the built-in file browser is used or not), the submenu for some elements will become empty.

MacOS 11.5.2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/15073200/131962714-9aea79f6-2d6a-412d-8c6b-c40a98d5e356.mp4

**Comment by circular17** [comment]
Seems to be fixed
