### ISSUE TITLE
The hint continues to be displayed on top of other windows on Mac and Linux

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#253]
When you open the window of another program, the hint continues to be displayed on top of the other program. When the main window of LazPaint is minimized, the hint continues to be displayed.
This behaviour is common for Mac and Linux.

MacOS 11.5.2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/15073200/131963564-a55ca7f7-6d0e-4cb9-ad1f-f3aaebc1a217.mp4

Ubuntu 20.04.2:
![Screenshot from 2021-09-02 17-08-12](https://user-images.githubusercontent.com/15073200/131963966-2c86e9d7-e161-4ef2-9946-a6c70c447c7a.png)

**Comment by circular17** [comment]
Yes, that's kind of normal.
