### ISSUE TITLE
Panels in the undocked state continue to be displayed on top of other windows on Mac and Linux

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#254]
The "toolbox" and "layers and colors" panels in the undocked state continue to be displayed on top of other windows.
This behaviour is common for Mac and Linux.

MacOS 11.5.2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/15073200/131965208-b95cb398-3206-4695-b468-e5fd73f4d81b.mp4

Ubuntu 20.04.2:
![Screenshot from 2021-09-02 17-09-49](https://user-images.githubusercontent.com/15073200/131965266-562f6726-a49c-4d6c-8ad5-d08c88b3da13.png)

**Comment by circular17** [comment]
Yes that's a bug in Lazarus.
