### ISSUE TITLE
Docked to right toolbox can't display submenu normally

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#255]
If the toolbox docked to right, then part of the submenu disappears.
If you stretch the program window so that the second toolbox column disappears, then there will be no submenu at all.

This behaviour is common for MacOS 11.5.2, Windows 10 (21H1 19043.1083), Ubuntu 20.04.2.

https://user-images.githubusercontent.com/15073200/131966593-67cf5003-3945-4b84-b1e2-b615652062f3.mp4

**Comment by c-sanchez** [comment]
hahahaha all this time and I didn't see that detail, I always have it on the left, good eye :)

**Comment by circular17** [comment]
fixed on dev
