### ISSUE TITLE
Saving a file with an incorrect name on Windows and Linux

### ISSUE THREAD

**Issue by EvgeniyDoctor** [bgrabitmap/lazpaint#256]
On Windows I was able to save files with the following names:
- `:.png` (there is no this file in Windows Explorer)
- `\.png` (in Windows Explorer name of this file: `.png`. In LazPaint name of this file after saving: `\\.png`)
- `/.png` (in Windows Explorer name of this file: `.png`. In LazPaint name of this file after saving: `\/.png`)

On Linux I saved file with `/.png` name. In the file manager the file name is `.png`, so it's hidden.

Windows 10 (21H1 19043.1083)
Ubuntu 20.04.2
LazPaint 7.1.6 (64-bit)

![Wrong filenames](https://user-images.githubusercontent.com/15073200/131967929-48344849-48b7-43fe-a483-eb22674704d7.png)

**Comment by circular17** [comment]
Thanks for all the feedbacks <3

**Comment by circular17** [comment]
done on dev
