### ISSUE TITLE
Incorrect work of the Deformation grid

### ISSUE THREAD

**Issue by Biche-oolUS** [bgrabitmap/lazpaint#258]
Image artifacts appear with extreme stretching
<img width="960" alt="1" src="https://user-images.githubusercontent.com/90157501/132141448-46d6da15-98a3-4814-9015-b964a5c34a57.png">
<img width="960" alt="2" src="https://user-images.githubusercontent.com/90157501/132141454-5795a40e-7956-48ac-841f-d03369048ebc.png">

**Comment by circular17** [comment]
Indeed.

**Comment by circular17** [comment]
fixed on dev. note that when mutliple extreme deformation overlap, there is still some glitch
