### ISSUE TITLE
EIntOverflow with 32 bit binary

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#26]
![lazpaint](https://user-images.githubusercontent.com/4131395/42726510-f51ece9a-876b-11e8-9e16-7538a6e69770.PNG)

```
        {$hints off}
        ec.red := (ec.red*($FFFF-gray)+level*gray) shr 16;
        ec.green := (ec.green*($FFFF-gray)+level*gray) shr 16;
        ec.blue := (ec.blue*($FFFF-gray)+level*gray) shr 16;
        {$hints on} 
```

Hi, this happens when I run LazPaint 'Debug' 32 bit, compiled with Lazarus Trunk and FPC Trunk. When compiled in 'Debug' 64 bit it works fine.

I don't know if is still a good idea to mantain 32 bit Windows, since only really old PC still uses 32 bit.

**Comment by lainz** [comment]
Some statistics (mainly gamers, but I think graphic editing should be the same)
https://store.steampowered.com/hwsurvey/

**Comment by circular17** [comment]
Oops it seems I missed this issue. I fixed it with on dev branch:
```
        {$hints off}
        ec.red := (ec.red*(not gray)+level*gray) shr 16;
        ec.green := (ec.green*(not gray)+level*gray) shr 16;
        ec.blue := (ec.blue*(not gray)+level*gray) shr 16;
        {$hints on}
```
