### ISSUE TITLE
Font problem

### ISSUE THREAD

**Issue by pan7ae** [bgrabitmap/lazpaint#260]
When I want to increase this field, the font changes:
![image](https://user-images.githubusercontent.com/87745086/132513763-97932e48-8248-40c4-8cfd-2ad9876b9563.png)
![image](https://user-images.githubusercontent.com/87745086/132513952-aea890e6-ecd6-4f7b-ab14-a659694adc07.png)

**Comment by circular17** [comment]
Yes it adjusts to use the space optimally.
