### ISSUE TITLE
Rotation and language

### ISSUE THREAD

**Issue by pan7ae** [bgrabitmap/lazpaint#261]
When I want to create new file and choose transparent background there is arrow with background. Also title "Memory required" wasn't translated into Russian
![image](https://user-images.githubusercontent.com/87745086/132514130-813a3087-1039-4fab-b2ba-e6ec58def68f.png)
![image](https://user-images.githubusercontent.com/87745086/132514599-0c6a6b43-e086-4fd9-9ce1-73a299794ca9.png)

**Comment by circular17** [comment]
Yes. Russian translation is not complete. It will be in the next release (that's already done on dev branch).
