### ISSUE TITLE
Can't choose color

### ISSUE THREAD

**Issue by pan7ae** [bgrabitmap/lazpaint#263]
I can't choose color and I think user can't understand what this pink square and number mean
![image](https://user-images.githubusercontent.com/87745086/132516627-bb1259f8-e35a-4315-b465-ad995efeb7c3.png)
![image](https://user-images.githubusercontent.com/87745086/132516665-27329b03-ed31-4586-aded-f91e654ed9b3.png)

**Comment by c-sanchez** [comment]
To choose the colors you must right-click on that square.
You can choose the color also with the palette bar (right side), using left click for the pen and right click for the back.
That number (210 in the screenshot) is the opacity level.
The other number (53% in the screenshot) is the difference in the pen and background colors in percent, if you choose for example black and white, this will say 100%.

**Comment by circular17** [comment]
If you hover an element you get a description.

As c-sanchez points out, you can right-click on the color, or use the palette, or use the color chooser (display it with the View menu if it has been closed).
