### ISSUE TITLE
Auto lang defenition issue

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#274]
If the interface language definition set in "auto" then program UI will contain 2 languages at the same time: english + OS locale lang (RUS in my case)
![image1](https://user-images.githubusercontent.com/90435360/132851159-93b7d595-d6c7-4203-a361-7c1a702576cd.png)
![image2](https://user-images.githubusercontent.com/90435360/132851162-b80d54ae-cd32-4bb7-a28e-85424fd6170c.png)

**Comment by circular17** [comment]
This is because translation was not complete. It has been done on dev.
