### ISSUE TITLE
Element translation incorrect (Deselect)

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#276]
Translation of the element "Deselect" from drop-down list: "Select -> Deselect" to russian lang is wrong. "Удалить" means delete. This can lead to wrong conclusions.
![image8](https://user-images.githubusercontent.com/90435360/132855504-0e7616a8-069c-4bd1-a375-5f8dfa2886a7.png)

**Comment by circular17** [comment]
This menu is intended to delete the selection. Deselect is in the next menu.
