### ISSUE TITLE
"Paste As New Layer" element

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#277]
The [Paste As New Layer] element is located in one group with such elements as [Cut], [Copy], [Paste], [Deselect], but [Deselect] function does not apply to it.
![image7](https://user-images.githubusercontent.com/90435360/132857767-b60287f5-38ec-4cfd-97b7-aa3d521f68b6.png)
![image8](https://user-images.githubusercontent.com/90435360/132857773-3857fd5e-a6ab-4f92-abf9-ca2eef91051e.png)

**Comment by c-sanchez** [comment]
Huh? that is "Delete", to delete selection.

**Comment by Rick0dz** [comment]
> Huh? that is "Delete", to delete selection.

Well, it doesn't delete new layer anyway.

**Comment by circular17** [comment]
Hmm ok makes sense to delete selected layer

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/lazpaint/issues/389

**Comment by circular17** [comment]
Delete layer if Delete key or action is used with Move layer tool

**Comment by circular17** [comment]
done on dev
