### ISSUE TITLE
Error with [Edit Shape]

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#278]
The program throws an error (text in Notes) when you try to apply the [Edit Shape] tool (located on the left pane) to multiple active tool objects [Select Rectangle], after which the image disappears from the workspace or the whole workspace disappears (screenshots 2-3).

I couldn't reproduce the error, but at the same time, the use of tools from the left pane was one-timed. After a single use It was impossible to continue work with the same tool - it was resetted.

![image9](https://user-images.githubusercontent.com/90435360/132859175-35c31d9d-079d-4742-b0c0-2e38436ad080.png)
![image10](https://user-images.githubusercontent.com/90435360/132859184-7e52205c-44dc-40e1-80fe-73a02e687de9.png)
![image11](https://user-images.githubusercontent.com/90435360/132859185-8aa43431-581b-45b7-8e02-9535fc296122.png)

**Comment by circular17** [comment]
I don't encounter the error. It is likely to be fixed but if it happens again with the next release, details on such error would be welcome.
