### ISSUE TITLE
[Select Rectangle] tool used with other tools issue

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#279]
When [Select Rectangle] tool is used simultaneously with the such tools as [Polilyne], [Rectangle], [Polygon], [Text] then their contours, lines or characters (text) are not visible (become transparent).
![image12](https://user-images.githubusercontent.com/90435360/132861227-ba140673-7aab-4369-a14a-d7019d3291fc.png)
![image13](https://user-images.githubusercontent.com/90435360/132861312-ef07cc2b-c6b5-4e27-a208-a3c3d793a050.png)
![image14](https://user-images.githubusercontent.com/90435360/132861316-911a4d7a-ba52-4b12-a25a-f00c8d6a56ad.png)

**Comment by circular17** [comment]
Yes this is normal. The selection tool clips everything that is drawn. It is similar to a mask.
