### ISSUE TITLE
Compiling in trunk

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#28]
umultiimage.pas(74,30) Error: Only static methods and static variables can be referenced through an object type

**Comment by circular17** [comment]
Fixed on dev-vectorial branch, I will merge it soon with dev-bgrabitmap
(to solve it locally, simply add static keyword after the called method definition)

**Comment by lainz** [comment]
Hi, I switched to dev-vectorial and still not working.
I added static to the end of the method TFMultiImage.ShowAndChoose and says that static is not allowed here.

**Comment by lainz** [comment]
Sorry I found the problem was I switched only to dev-vectorial of lazpaint and not to dev-vectorial of bgrabitmap.

**Comment by circular17** [comment]
Hmmm I am surprised I though there was nothing in dev-vectorial of bgrabitmap

**Comment by lainz** [comment]
Still not compiling but for another reasons not static, maybe there are files missing?

**Comment by circular17** [comment]
What error do you get?

**Comment by lainz** [comment]
Using dev-vectorial in both sources I get:
ustatetype.pas(1058,19) Error: Identifier idents no member "SaveOriginalToStream"
ustatetype.pas(1075,72) Error: Wrong number of parameters specified for call to "AddOriginalFromStream"
bgralayers.pas(1262,29) Error: Found declaration: AddOriginalFromStream(TStream):LongInt;
ustatetype.pas(1084,65) Error: Identifier idents no member "OriginalGuid"
ustatetype.pas(1102,72) Error: Wrong number of parameters specified for call to "AddOriginalFromStream"
bgralayers.pas(1262,29) Error: Found declaration: AddOriginalFromStream(TStream):LongInt;
ustatetype.pas(1105,64) Error: Identifier idents no member "OriginalGuid"
ustatetype.pas(1112,64) Error: Identifier idents no member "OriginalGuid"

**Comment by circular17** [comment]
Hmm try setting branch to dev-bgrabitmap and pull the last changes

**Comment by lainz** [comment]
If I switch back to dev branch I get the original problem of static. Even pulling all new stuff.

**Comment by circular17** [comment]
Ok. What error do you get ?

**Comment by lainz** [comment]
umultiimage.pas(74,30) Error: Only static methods and static variables can be referenced through an object type

**Comment by circular17** [comment]
Ok. When you CTRL-Click to get the definition of Empty, what do you have?

**Comment by lainz** [comment]
Oh I see, I fixed it adding static into 2 class functions.
      class function Empty: TImageEntry; static;
      class function NewFrameIndex: integer; static;

**Comment by circular17** [comment]
Those are already on the latest dev-vectorial branch of LazPaint.

**Comment by lainz** [comment]
Ok thanks for adding it. Seems that I had missing the 2 latest commits.

**Comment by circular17** [comment]
Ok. Sorry for the confusion, I don't know why there is a dev-vectorial on bgrabitmap.

**Comment by lainz** [comment]
Ok, no problem. You can easily delete it from the web gui. But check if there is nothing inside that can be lost.

**Comment by circular17** [comment]
Yeah I don't want to loose my changes. Maybe I will wait after I merge LazPaint branch to be sure.

**Comment by circular17** [comment]
So in this dev-vectorial, I am making LazPaint compatible with the vector layers. Not adding yet the vectorial tools. Just that if you load something that contains an original, it will preserve it. For example something from vectoredit or the file generated by test/layeroriginal.
