### ISSUE TITLE
"Edit Selection" minimize issue

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#280]
If you minimize the "Edit Selection" window, it will permanently disappear. At the same time the "Color" window will remain, and the main window Lazpaint will be blocked from cursor clicks. When you try to close the main window through the OS panel (with active programs) or by using "Alt + F4" - a message "Progress action" will appear, but the program will not close or respond.
![image15](https://user-images.githubusercontent.com/90435360/132864926-c1440b02-7058-4f63-991f-14a679a6afd3.png)
![image16](https://user-images.githubusercontent.com/90435360/132864930-6006be65-50a5-4bea-8ae4-f7eac4401393.png)

**Comment by circular17** [comment]
Yes, it won't be possible anymore to minimize this window, to avoid such problem.
