### ISSUE TITLE
[Select rectangle] tool objects lose functions delete / cut / paste...

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#281]
New created by [Select rectangle] tool objects lose functions delete / cut / paste after applying the [Edit shape] tool to previous  created by [Select rectangle] tool objects.
![image17](https://user-images.githubusercontent.com/90435360/132867153-c60b0934-d721-43b6-867b-0f85c0a7fca8.png)
![image18](https://user-images.githubusercontent.com/90435360/132867160-57a322b0-dda7-4b72-9c8b-229ee1d3f218.png)
![image19](https://user-images.githubusercontent.com/90435360/132867163-efd90c2b-5af6-4955-8da0-340c3f8bb7d3.png)
![image20](https://user-images.githubusercontent.com/90435360/132867164-62ce3899-9175-438a-8d2e-43b687b3d507.png)

**Comment by circular17** [comment]
I suppose the background was extracted only with the first 2 rectangles. After that the layer contained image data, and so deleting would only delete this data. This is expected behavior, though I understand it may not be obvious.
