### ISSUE TITLE
Сanvas size changing error

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#282]
When changing the size of canvas (by selecting % as measurement units), if you enter the maximum value (8192) to any of the fields (width / height), and in the other, you drive a huge number (with keyboard) (for example: 99999999999999999999999999999999999999), and immediately pressing the "OK" button - program throws an error.
Such an error occurs in all cases when you can edit image / canvas size, having opportunity to enter arbitrarily large numbers by keyboard (approx. screen 3).
The same happens when units of measurement set to"PX", but the number to enter must be much larger.
![image21](https://user-images.githubusercontent.com/90435360/132872136-e6cb3ef5-2d7f-41fc-b5fb-7682240e73dc.png)
![image22](https://user-images.githubusercontent.com/90435360/132872140-c02fe930-2194-4f43-b94d-1b73dbdb5201.png)
![image23](https://user-images.githubusercontent.com/90435360/132872142-15f6a0c9-a681-4b9b-b395-e9dc3fdb54ac.png)

**Comment by circular17** [comment]
Thank you very much for reporting the bug

**Comment by circular17** [comment]
fixed on dev by limiting percentage values
