### ISSUE TITLE
Rain : range quantity issue

### ISSUE THREAD

**Issue by Rick0dz** [bgrabitmap/lazpaint#284]
Range of rain quantity tool works incorrect.
- increment of rain drops amount works instantly, but decrease - starting to work after 4-5 seconds timespan (especially when moving from MAX to MID/MIN state). It makes an impression of function failure;
- If you do not drag the slider with the cursor, and just press it on the range the slider only changes the extreme positions (MAX / MIN).
![image25](https://user-images.githubusercontent.com/90435360/132877588-93c1b18f-eee1-4ca6-9574-7e1df9574a6b.png)

**Comment by circular17** [comment]
Fixed by Lulu04 on dev branch
