### ISSUE TITLE
Dropdown panel "Pen" and "Back" disappears without moving cursor

### ISSUE THREAD

**Issue by shaitanmind** [bgrabitmap/lazpaint#287]
Steps to reproduce:
1. open LazPaint 
2. move cursor on "Pen" or "Back" panel 
3. click on any arrow on dropdown panel without moving cursor within 3-4 sec 

Expected result:
Panel stay still until we reached needed value

Actual result:
Panel disappears while we keep clicking

(OS Win 10)

**Comment by circular17** [comment]
Indeed.

**Comment by circular17** [comment]
Todo: reset the timer by calling the show panel function when changing the opacity.

**Comment by circular17** [comment]
done on dev
