### ISSUE TITLE
Highlighted language doesn't match actual language after cancel language switching

### ISSUE THREAD

**Issue by shaitanmind** [bgrabitmap/lazpaint#288]
Steps to reproduce:

1. open LazPaint and draw something 
2. go to File menu 
3. open Language menu 
4. click on any different language 
5. click "Cancel" in opened dialog window

Expected result:
No any changes in language menu

Actual result:
Highlighted language doesn't match actual language in the program

(OS Win 10)

**Comment by circular17** [comment]
Fixed on dev
