### ISSUE TITLE
Untranslated text in Ru localization:

### ISSUE THREAD

**Issue by shaitanmind** [bgrabitmap/lazpaint#290]
Untranslated text in Ru localization
- "Файл" menu:
Choose entry...
Save in same folder...
Export...
Print...
Use image browser
Remember save format
Forget dialog box answers

- "Редактирование" menu:
Paste as new layer
Move up
Bring to front
Move down
Send to back
Align shape (and all items in the dropdown menu)
Convert shape to curve

- "Выделить" menu:
Flip selection horizontally
Flip selection vertically

- "Просмотр" menu:
Image list (and all items in the opened window)
Status bar
Dock toolbox
Dock layers and colors
Fullscreen
Dark theme
Set workspace color...
Icon size (and all items in the dropdown menu)

- "Изображение" menu:
Swap red and blue channels

- "Цвета" menu:
Curves...
Posterize...
Complementary colors

- "Инструмент" menu, tool panel:
Change docking (on tool panel only)
Brush
Clone tool
Edit shape
Polyline
Opened curve
Curve (on tool panel only)

- "Фильтр" menu:
in "Радиальное размытие" item Box blur...
Noise filter...
ClearType
Обратный ClearType
Wave displacement...

- "Визуализация" menu:
Rain...

- Script menu (all items)
- Dropdown hints on top panel:
Choose entry within file
Texture fill and Preview on "Перо" and "Назад" panel
Gradient repetition...(and items in the dropdown menu), Start opacity, Switch color, End opacity on dropdown "Назад" panel
Disable antialiasing (when tool "Перо"(Pen) enabled)
Make transparent, Sharpen, Soften, Lighten, Darken when tool "Ластик" enabled
Spacing between patterns, Create geometric brush, Load brush from file..., Remove current brush, panels Brush and Spacing when tool Brush enabled
Pen style when tool "Прямоугольник" enabled
No dropdown hints on the left side of the top panel (Cap style) when tool Polyline enabled (start and end of line), Horizontal size of arrow, Vertical size of arrow untranslated.
Types of curve in dropping out menu, Move point, Autodetect angles, Draw an angle, Draw a curve when tool Opened Curve enabled
Text size, Align left, Center, Align right when tool "Текст" enabled
Edit gradient/texture points, Adjust to shape when tool "Отображение текстуры" enabled
Ratio when tool "Выделение в виде прямоугольника" enabled

- Palette panel:
Add color to palette
Remove color to palette
Palette options (and all items in the dropdown menu)

- Layer panel:
Raster layer
Select blend operation
Zoom layer stack in
Zoom layer stack out
Rasterize layer
Zoom layer

- Tips for the first selection of any tool

**Comment by circular17** [comment]
Most likely fixed on dev
