### ISSUE TITLE
Unexpected slider (trackbar) movement in geometric brush settings

### ISSUE THREAD

**Issue by shaitanmind** [bgrabitmap/lazpaint#291]
Unexpected slider (trackbar) movement in geometric brush settings
Steps to reproduce:
1. open LazPaint 
2. select Brush tool 
3. click on Create geometric brush 
4. click to some place on the trackbar several times

Expected result:
The slider moves to the desired position

Actual result:
The slider jumps between two wrong positions

**Comment by circular17** [comment]
Yes, that's how this component works. To get to the correct position, you need to drag the indicator.
