### ISSUE TITLE
Tools window issue on MacOS

### ISSUE THREAD

**Issue by Sotren** [bgrabitmap/lazpaint#292]
Steps to reproduce:
    1. Open LazPaint;
    2. Unlock toolbox;
    3. Close tools window ;
    4. Switch theme from dark to white;
    5. Open tools window.
    
Expected result:
standard tools window with white color
![Standard tools window](https://user-images.githubusercontent.com/44051575/134874423-171aba9f-eb58-4843-8e43-f064e2f042d5.png)

 

Actual result:
Tools window with no icon in it.
![tools window issue ](https://user-images.githubusercontent.com/44051575/134872659-a5ad2d79-77b4-4910-a26c-cef9e88a76a4.png)

(macOs Catalina v 10.15.7)

**Comment by circular17** [comment]
related to https://github.com/bgrabitmap/lazpaint/issues/252

**Comment by circular17** [comment]
Seems to be fixed
