### ISSUE TITLE
Dock toolbox issue on MacOS

### ISSUE THREAD

**Issue by Sotren** [bgrabitmap/lazpaint#293]
Steps to reproduce:
1. Open LazPaint;
2. Unlock toolbox;
3. Close tools window ;
4. Switch theme to dark or white;
5. Open doc toolbox.

Expected result:
No changes, expect different  color 
![Expected result](https://user-images.githubusercontent.com/44051575/134880801-ed67a7ef-ef99-42b6-9f08-583d8d389a3f.png)

Actual result:
expanded form tool box are empty.
![Actual result](https://user-images.githubusercontent.com/44051575/134881491-9b8e2c0c-577a-48bf-b449-62ea277e7bf0.png)

(macOs Catalina v 10.15.7)

**Comment by circular17** [comment]
related to https://github.com/bgrabitmap/lazpaint/issues/252

**Comment by circular17** [comment]
Seems to be fixed
