### ISSUE TITLE
Saiving  webp issue 

### ISSUE THREAD

**Issue by Sotren** [bgrabitmap/lazpaint#294]
Steps to reproduce:
1 saving with webp format 
 
Expected result:
just regular saving 

Actual result:
Program get complete frozen until user don't press any key on keyboard

https://user-images.githubusercontent.com/44051575/134894201-e6d2a034-2d0c-41bf-a768-789778708ca4.mp4

**Comment by circular17** [comment]
Thanks for the feedback. This is probably fixed on dev.
