### ISSUE TITLE
inability to load the selected area

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#297]
menu - "Select" - "Load selection" - select a previously saved selection in bmp format

Error loading previously saved selection. The description of the error does not match the reason.
you need to either remove the ability to save the selection area in unsupported formats or implement support

Errors:

LoadSelection
Access violation

FileLoadSelection
Access violation
![3-1](https://user-images.githubusercontent.com/42349207/134938489-6cc1bc43-1ea9-4131-b4c2-b9473e5d59b7.png)
![3-2](https://user-images.githubusercontent.com/42349207/134938496-e285c439-9333-4e44-bcff-1e18b2616063.png)

**Comment by circular17** [comment]
Thanks for reporting.

That's fixed on dev
