### ISSUE TITLE
Sticky click in motion blur

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#300]
Menu - "Filter" - "Motion blur"

Leaving with the mouse button held down from the window with a choice of the direction of blur leads to sticking of the button press.

https://user-images.githubusercontent.com/42349207/134939726-a4b84af6-6124-48c4-b9e4-4db2ed074501.mp4

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/320

**Comment by circular17** [comment]
Indeed

**Comment by circular17** [comment]
To do: disable the modification mode if the button is not down in the shift state of the MouseMove event.

**Comment by circular17** [comment]
done on dev
