### ISSUE TITLE
Incorrect cancellation of save

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#301]
menu - File - Language - ru - Yes - Cancel
when you restart the program and offer to save the current project, at the stage of choosing the format\file name, the cancellation still leads to a restart of the program and the loss of the project.

https://user-images.githubusercontent.com/42349207/134941002-33da34a4-9085-4719-88b1-c318ad69a091.mp4

**Comment by circular17** [comment]
Fixed on dev
