### ISSUE TITLE
loss of focus when resizing the brush

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#305]
https://user-images.githubusercontent.com/42349207/134942783-a4838253-f267-46d1-b95b-b1fa0674633b.mp4

When you change the size of the brush with the mouse wheel and Alt key, the focus flies to the menu.

**Comment by circular17** [comment]
Might be fixed just by handling the Alt key (setting the Handled boolean in the events for tools with brush/pen size).

**Comment by circular17** [comment]
done on dev
