### ISSUE TITLE
inability to exit/cancel the "Deformation grid" when no deformation done

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#309]
If you select the "Deformation grid" tool and do not manipulate the warp mesh, you cannot cancel the tool either by pressing Enter, Esc or Ctrl + Z. Cancellation becomes possible if you change the grid.

**Comment by circular17** [comment]
The grid tool always have the grid visible. So in theory there is nothing to cancel. Though the Escape key could escape this tool and go back to the Hand tool.

**Comment by circular17** [comment]
done on dev
