### ISSUE TITLE
the selection is not drawn 

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#311]
When you select with the "Select polygon" or "Select curve" tool by scaling with the mouse wheel and moving the mouse, the selection area will not be drawn until the mouse stops moving.

windows 7 7601

https://user-images.githubusercontent.com/42349207/134946700-d1203435-8f8a-440d-9194-3d2fa138d2aa.mp4

**Comment by circular17** [comment]
Redrawing the whole selection after zooming can take some time, so the application waits for the user to be idle to do that. So this is kind of expected.
