### ISSUE TITLE
fatal error

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#312]
"Select rectangle" - "Move selection" - Yes - move the resulting area - "Deformation grid"

Error messages. For further work, you need to restart LazPaint through the task manager, although LazPaint responds.

windows 7 7601

https://user-images.githubusercontent.com/42349207/134948320-49c2643b-a200-4a96-9f75-7101d33e16c7.mp4

**Comment by circular17** [comment]
Fixed on dev
