### ISSUE TITLE
fatal error 

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#313]
select area - tool "Edit shape" - "Texture mepping" - "Deformation grid" - "Undo last modification"

Cancellation of the last action led to multiple error messages superimposed on each other, the program crashed.

the error could not be reproduced again

windows 7 7601

![19](https://user-images.githubusercontent.com/42349207/134948814-c8e7ff3f-3450-469b-b86e-77d48dbe7dc1.png)

**Comment by circular17** [comment]
I think it is fixed on dev branch
