### ISSUE TITLE
Brush size is not displayed

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#315]
"draw selection with pen" tool

there is no display of the brush size at the cursor position, which makes using the tool extremely inconvenient 

https://user-images.githubusercontent.com/42349207/134949425-fd2133d7-21a4-46a1-8727-38a58c71f2cc.mp4

**Comment by circular17** [comment]
That's a good point

**Comment by circular17** [comment]
Can be implemented the same way as for the brush tool

**Comment by circular17** [comment]
done on dev
