### ISSUE TITLE
redundant message 

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#316]
When opening an unsupported file format, two messages are displayed, the second with an error is redundant.

windows 7 7601

![22-1](https://user-images.githubusercontent.com/42349207/134949826-84d53e0d-6a81-40fa-8092-3b2d775788b8.png)
![22-2](https://user-images.githubusercontent.com/42349207/134949829-e9714a40-a7ba-47f1-bac6-fb9bd923347b.png)

**Comment by circular17** [comment]
Thanks for the feedback.

This is probably fixed on dev.
