### ISSUE TITLE
incorrect "Undo last modification"

### ISSUE THREAD

**Issue by Kramolnikk** [bgrabitmap/lazpaint#317]
"Undo last modification" does not work correctly, skipping a step after the following manipulations:
menu - "image" - "rotate 180"
menu - "image" - "horizontal reflection"
or
menu - "image" - "rotate 180"
menu - "image" - "vertical reflection"
etc.

If this behavior is somehow justified for actions of the same type "turn 90 clockwise - turn 90 clockwise", then no actions above.

**Comment by circular17** [comment]
Yes, the action rotate 180 + horizontal reflection are combined and becomes simply vertical flip. This avoids having too many items in the undo list when doing many times such transformations.
