### ISSUE TITLE
Icon PX cancel issue

### ISSUE THREAD

**Issue by Sotren** [bgrabitmap/lazpaint#319]
Steps to reproduce:
1 drew something in the layer
2  open view Icon size choose 
3  select different PX size and press cancel

Expected result:
non changes will be applied

Actual result:
PX will change even if you cancel agreement, and when you restart the program it will be in different PX icon size

https://user-images.githubusercontent.com/44051575/135034490-048d1c2f-f1b7-459f-832e-655865d1f282.mp4

(macOs Catalina v 10.15.7)

**Comment by circular17** [comment]
Thanks for the feedback. It is fixed on dev.
