### ISSUE TITLE
Sticky keys "Motion Blur"

### ISSUE THREAD

**Issue by Wixenia** [bgrabitmap/lazpaint#320]
Filter -> Motion Blur. When you press it, sticking to the key is periodically triggere

https://user-images.githubusercontent.com/44490229/135630669-674fee1c-8ab2-47f8-a899-e5c0bc688327.mp4

d.

**Comment by circular17** [comment]
Thanks for the feedback. What do you mean by sticky keys?

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/300
