### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by Wixenia** [bgrabitmap/lazpaint#321]
Selecting an area - the tool "Edit Shape" - "Transform Texture" - "Warp Mesh" - this action led to the imposition of several error messages on top of each other, the program crashed, but did not close. Further actions with the program are impossible. Closing the program through the task manager.

https://user-images.githubusercontent.com/44490229/135632763-fab03e0e-621f-451e-aa26-c59b203f73c5.mp4

**Comment by circular17** [comment]
I think it is fixed on dev branch

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/313
