### ISSUE TITLE
Brush

### ISSUE THREAD

**Issue by Wixenia** [bgrabitmap/lazpaint#324]
When using a brush, choosing a color changes the color in the second box and will be applied when using the right mouse button instead of the left one. When using the left button, the color remains the same.

https://user-images.githubusercontent.com/44490229/135637587-81654e20-8fc3-47f2-8731-1df5fb25185c.mp4

**Comment by circular17** [comment]
One need to click on the color preview of the pen (blue rectangle) in the top toolbar to select the pen color in the color chooser.
