### ISSUE TITLE
Incomplete localization

### ISSUE THREAD

**Issue by Orion8V** [bgrabitmap/lazpaint#327]
LP_03
Summary			Incomplete localization
Project			LazPaint
Component		Аpplication, GUI
Version			7.1.16
Severity		Critical
Priority		Defined by the project manager
Status			New
Author			Victor D., dvvbox@mail.ru
Assigned To		-
Environment		Windows 7 32-bit SP1, CPU Intel Core 2 Quad Q6700 2,66GHz, RAM 4Gb, GPU Gigabyte GeForce GTX 660 Ti, HDD WD Caviar Blue 640Gb
Steps to Reproduce	Explore application menu
Result			Incomplete localization of the application
Expected Result		Сomplete localization of the application
Attachment		LP_03.jpg
![LP_03](https://user-images.githubusercontent.com/92079144/136644113-971e4e3a-29d7-4ce3-aed6-4b85237b0013.jpg)

**Comment by circular17** [comment]
More translations for Russian have been provided.
