### ISSUE TITLE
Inability to open a texture file after creating it

### ISSUE THREAD

**Issue by Orion8V** [bgrabitmap/lazpaint#332]
LP_08
Summary			Inability to open a texture file after creating it
Project			LazPaint
Component		Аpplication
Version			7.1.16
Severity		Critical
Priority		Defined by the project manager
Status			New
Author			Victor D., dvvbox@mail.ru
Assigned To		-
Environment		Windows 7 32-bit SP1, CPU Intel Core 2 Quad Q6700 2,66GHz, RAM 4Gb, GPU Gigabyte GeForce GTX 660 Ti, HDD WD Caviar Blue 640Gb
Steps to Reproduce	Open a file with an image, edit it, save it, click Create a new file, click Texture mapping in the Toolbar, select the saved file
Result			Image not loaded
Expected Result		Image loaded
Attachment		LP_08.mp4

https://user-images.githubusercontent.com/92079144/136644646-85c38696-ffed-4028-9f2b-2abcb8cedcaf.mp4

**Comment by circular17** [comment]
The texture tool is do draw and transform a texture. After loading the texture, you need to click in the image to draw a rectangle that will hold the texture.
