### ISSUE TITLE
Incomplete translation into Russian

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#334]
``Full description - not all tools (brush, edit shape), opening windows (Spacing) and floating hints have been translated into Russian.
Reproducibility – always. 
Severity – Minor.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce - Any file is open. View the menu on the main panel (editing, tools), select Clone tool and use this tool
Additional Information – report1.png,  #report1(1).png
![report1](https://user-images.githubusercontent.com/92689012/137639699-93988ffc-db28-4920-9f15-6e1ed02b94fe.png)
![report1(1)](https://user-images.githubusercontent.com/92689012/137639705-2824e958-ebbd-49be-8a1d-1c07b8c11d42.png)

**Comment by circular17** [comment]
Fixed on dev
