### ISSUE TITLE
Some hints are missing

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#335]
Full description - when selecting tools polyline or curve a hint does not pop up that you need to click on the right mouse button to complete the shape
Reproducibility – always. 
Severity – Minor.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce – Any file is open. Сhoose polyline or curve, take a few steps to get the shape - there is no message on how to complete the shape

**Comment by circular17** [comment]
Indeed

**Comment by circular17** [comment]
done on dev
