### ISSUE TITLE
Incorrect window title

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#338]
Full description - The title of the window is not fully written
Reproducibility – always. 
Severity – Minor.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce - Any file is open. Menu "filter", tool "apply function".
Additional Information – report5.png
![report5](https://user-images.githubusercontent.com/92689012/137639826-a5879544-1455-4945-8000-676e6bfc8299.png)

**Comment by circular17** [comment]
fixed on dev
