### ISSUE TITLE
Warning unhandled exception

### ISSUE THREAD

**Issue by GoncharovaNatalia** [bgrabitmap/lazpaint#340]
Full description - Warning unhandled exception
Reproducibility – not tested. 
Severity – Major.
Environment – Windows 10 (64-bit), LazPaint 7.1.6 (64-bit)
Steps To Reproduce - Difficulty in reproducing
Additional Information – report7.jpg
![report7](https://user-images.githubusercontent.com/92689012/137639935-51359416-2129-4fac-a2db-a8568705d285.JPG)

**Comment by circular17** [comment]
This is probably fixed in dev
