### ISSUE TITLE
localization of the product is not completed

### ISSUE THREAD

**Issue by Artshrayner** [bgrabitmap/lazpaint#342]
Summary: localization of the product is not completed
Steps: review all the tools and tabs on the menu bar for localization
Actual result: localization of the product is not completed
Expected result: localization of the product is completed
Severity: S1 (Minor)
Project LazPaint
Version 7.1.6 
Environment: Windows 10 (64-bit)

![1 bag - incomplete localization](https://user-images.githubusercontent.com/92594084/137888726-be1d409e-cffa-4606-b216-051280458d67.jpg)

**Comment by circular17** [comment]
most of it has been translated in Russian on dev
