### ISSUE TITLE
The drop-down submenu on the toolbar is frozen

### ISSUE THREAD

**Issue by Artshrayner** [bgrabitmap/lazpaint#343]
Summary: The drop-down submenu on the toolbar is frozen
Steps: 1. Hover the mouse cursor over the icon of any of the tools on the toolbar with a drop-down submenu;
2. Remove the mouse cursor from this icon.
Actual result: 1. The tool submenu is appeared;
2. The submenu is stayed on the screen for a short time.
Expected result: 1. The tool submenu is appeared;
2. The tool submenu is closed.
Severity: S2 (Major) 
Project LazPaint
Version 7.1.6
Environment: Windows 10 (64-bit)

![2 bag - freeze](https://user-images.githubusercontent.com/92594084/137889947-c30e7f4a-ff53-4489-b580-53438ba7bb55.jpg)

**Comment by circular17** [comment]
Yes that's on purpose, so that if you go a bit outside of the menu it doesn't disappear straight away
