### ISSUE TITLE
Replacement "Eraser" by cursor 

### ISSUE THREAD

**Issue by YuriyZubko** [bgrabitmap/lazpaint#345]
**1.     Description**
Replacement "Eraser" by cursor when decrease size
**2.	Environment**
Windows 10 Build 19043.1288
LazPaint  ver 7.1.6.0 RU version
**3.	Steps to reproduce**
1. Create new project
2. Check zoom 100%
3. Check "Eraser"
4. Decrease Width of eraser to 60

**4.	Expected result**
Regardless of size of eraser he don't change form
**5.	Actual result**
Eraser change form 
**6.	Attachment**

https://user-images.githubusercontent.com/92620013/137911888-61c2c923-f414-4fb5-b7e5-0e065ada391d.mp4

**Comment by circular17** [comment]
Yes, it is because it would be too small to easily see the cursor. You can zoom in the image though to have the expected cursor.
