### ISSUE TITLE
Aspect ratios list only for landscape orientations

### ISSUE THREAD

**Issue by AlexeyMischuk** [bgrabitmap/lazpaint#350]
### Description
While you create a new project, you can choose the aspect ratio of picture. But in the list there are only landscape orientation ratios, even if you manually change the orientaion of canvas - list doesn't change.

### Environment
Windows 10 Pro 64-bit (18362.356)
LazPaint 7.1.6 (64-bit)

### Reproduction steps
- Create new project (File → New..)
- In opened window fill the forms:
    - Width: 500
    - Heght: 800
- Open "Ratio" drop-down list

### Actual result
In the list only landscape orientaion ratios (4:3; 16:9)

![aspect ratio](https://user-images.githubusercontent.com/93237623/139003752-77e37c8c-231b-4241-825b-c2a79ab1ad03.png)
### Expected result
List contains ratios accordingly selected page orientation

**Comment by circular17** [comment]
Thanks for the feedback. That's indeed a possible improvement.

In the meantime, you can choose the corresponding landscape ratio and then click the rotating green arrow.

**Comment by circular17** [comment]
done on dev, also better handling of computation of ratios
