### ISSUE TITLE
Button text does not fit into button frame

### ISSUE THREAD

**Issue by AntoninaManzhela** [bgrabitmap/lazpaint#352]
**Description**
Button text "Увеличить, полностью вписав" does not fit into button frame in "Print" menu

**Environment**
Windows 10 64-bit
LazPaint 7.1.6 (64-bit)

**Steps to reproduce:**
1 Select File from the menu bar
2 in the dropdown window select Print
or use hot keys "Ctrl+P"

**Expected result**
button text "Увеличить, полностью вписав" is inscribed in button frames

**Actual result**
the text of the button "Увеличить, полностью вписав" is outside the border of the button

![Текст не влезает в кнопку1](https://user-images.githubusercontent.com/93258577/139053604-913c66e5-bc3f-4232-b937-c68865e5c559.png)

**Comment by circular17** [comment]
duplicate of https://github.com/bgrabitmap/lazpaint/issues/412
