### ISSUE TITLE
Missing space in window title.

### ISSUE THREAD

**Issue by AntoninaManzhela** [bgrabitmap/lazpaint#354]
**Description**
Grammatical defect in the title of the window "Редактироватьтекстуру". There is no space between words.

**Environment**
Windows 10 64-bit
LazPaint 7.1.6 (64-bit)

**Steps to reproduce**
1 create a new file
2 select Texture Mapping on the toolbar
3 select any picture as texture
4 select texture preview on the toolbar
5 texture editing window opens 

**Expected result**
there is a space between the words in the title of the window "Редактировать текстуру"

**Actual result**
there is no space between words in the title of the window
![Грамматический дефект](https://user-images.githubusercontent.com/93258577/139054221-02bb3284-23f1-4a86-874f-374ababc72c8.PNG)

**Comment by circular17** [comment]
fixed on dev
