### ISSUE TITLE
Non-functional buttons in settings tool Texture

### ISSUE THREAD

**Issue by AntoninaManzhela** [bgrabitmap/lazpaint#355]
**Description**
Buttons "Edit gradient/te points" and "Adjust to shape" do not respond

**Environment**
Windows 10 64-bit
LazPaint 7.1.6 (64-bit)

**Steps to reproduce**
1 open a file or create a new one
2 select the texture mapping tool
3 on the top toolbar, click the buttons "Edit gradient/te points", "Adjust to shape"

**Expected result**
the selected settings are applied

**Actual result**
buttons do not respond to click

https://user-images.githubusercontent.com/93258577/139054444-82c8d90f-7f66-4981-9510-60bda39ceafc.mp4

**Comment by circular17** [comment]
Yep, these buttons are only available when editing a shape.
