### ISSUE TITLE
Untranslated function names in the drop-down list in the menu bar in the Russian version

### ISSUE THREAD

**Issue by Tivotar** [bgrabitmap/lazpaint#357]
**Severity**: Minor.
**Priority**: Medium.
**Description**:The translation is partially missing in the name of the functions in the drop-down list in the menu bar in the Russian version.
**Environment**:Windows 10 build 19042.1288, LazPaint 7.1.6 (64-bit).
**Preconditions**:The program is launched, the Russian language is set.
**Steps to reproduce**:
1.Click on the "Файл" button in the menu bar.
**Actual result**: Some functions in the drop-down list are not translated.
**Expected result**: A drop-down list opens with a set of functions completely in Russian.
**Attachment**:
![image](https://user-images.githubusercontent.com/93270625/139090910-d96f0e2e-d479-4b89-95f2-de044e8a916c.png)

**Comment by circular17** [comment]
translation recently provided (in dev)
