### ISSUE TITLE
Incorrect translation of the "Light" label next to the color wheel.

### ISSUE THREAD

**Issue by Tivotar** [bgrabitmap/lazpaint#359]
**Severity**: Minor.
**Priority**: Medium.
**Environment**:Windows 10 build 19042.1288, LazPaint 7.1.6 (64-bit).
**Preconditions**:The program is launched, the Russian language is set.
**Steps to reproduce**:
1.Click on the "Texture fill" button in the toolbar.
2.Select any picture.
3.Select texture preview.
**Actual result**: The inscription is called "Свет".
**Expected result**: The inscription is called "Яркость".
**Attachment**:
![image](https://user-images.githubusercontent.com/93270625/139092264-2e6e1387-7b70-4cba-af72-804ab1eb3a64.png)

**Comment by circular17** [comment]
done on dev
