### ISSUE TITLE
There is no word separation in the title of the "Редактировать текстуру" window.

### ISSUE THREAD

**Issue by Tivotar** [bgrabitmap/lazpaint#360]
**Severity**: Minor.
**Priority**: Medium.
**Description**:There is a grammatical error in the title of the window, there is no space between words.
**Environment**:Windows 10 build 19042.1288, LazPaint 7.1.6 (64-bit).
**Preconditions**:The program is launched, the Russian language is set.
**Steps to reproduce**:
1.Click on the "Texture fill" button in the toolbar.
2.Select any picture.
3.Select texture preview.
**Actual result**: The window is called "Редактироватьтекстуру".
**Expected result**: The window is called "Редактировать текстуру".
**Attachment**:
![image](https://user-images.githubusercontent.com/93270625/139092461-45d6ec68-a9d2-4eb8-8a9e-85395db3c99f.png)

**Comment by circular17** [comment]
fixed on dev
