### ISSUE TITLE
Incorrect position of hint popup.

### ISSUE THREAD

**Issue by Tivotar** [bgrabitmap/lazpaint#361]
**Severity**: Minor.
**Priority**: Medium.
**Description**: Warning messages are displayed in the center of the main screen, not in the center of the program window.
**Environment**:Windows 10 build 19042.1288, LazPaint 7.1.6 (64-bit).
**Preconditions**:The program is launched, the Russian language is set.
**Steps to reproduce**:
1.lick on the "Перспектива слоя" button in the toolbar.
**Actual result**: Warning messages are displayed in the center of the home screen.
**Expected result**: Warning messages are displayed in the center of the program window.
**Attachment**:
![image](https://user-images.githubusercontent.com/93270625/139093352-5fa941ef-254c-41b9-9723-6ad56a609bf4.png)

**Comment by circular17** [comment]
Fair point.

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/347
