### ISSUE TITLE
Uneven translation into different languages

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#364]
**1. Summary:**
Uneven translation into different languages.
**2. Description:**
Uneven translation into different languages. Chinese and Russian were compared.
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Press File -> Language -> ru
Move the cursor over the top menu items one by one
Press File -> Language -> zh_CH
Move the cursor over the top menu items one by one
**5. Expected result**
Full translation into all available languages.
**6. Actual result**
Uneven translation into Russian and Chinese languages.
**7. Attachment:**
https://user-images.githubusercontent.com/89531854/139294918-469b2ef9-567e-4d00-814f-b01ff5725a47.mov

**Comment by circular17** [comment]
Yes sometimes translations do not arrive as quickly. It depends on translators.

Chinese is fully translated and Russian will be in the next release.

Only scripts are not translated. That's something to consider indeed:
https://github.com/bgrabitmap/lazpaint/issues/374
