### ISSUE TITLE
Unstable donation link

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#365]
**1. Summary:**
Unstable donation link.
**2. Description:**
The donation link is unstable. Sometimes it works, sometimes it doesn't.
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Press to Donate.
**5. Expected result**
The link will open with little waiting.
**6. Actual result**
Sometimes the link won't load.
**7. Attachment:**
https://user-images.githubusercontent.com/89531854/139295434-78fbf976-b109-40b1-922b-2b861a6791a2.mp4

**Comment by circular17** [comment]
seems browser/internet connection related
