### ISSUE TITLE
The window becomes inactive

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#367]
**1. Summary:**
The window becomes inactive.
**2. Description:**
The window does not become inactive after closing another application window, although it was the last active one before that
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Right click on 'Preview';
Close new open window.
**5. Expected result**
The previous LazPaint window will be active.
**6. Actual result**
The last active non-LazPaint window is activated.
**7. Attachment:** 
https://user-images.githubusercontent.com/89531854/139295909-e43a6f51-3816-4df5-b975-f435dde1bd06.mp4

**Comment by circular17** [comment]
this is handled by the window manager. this problem will be solved when lazpaint will handle multiple documents
