### ISSUE TITLE
Problem with posterize levels

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#368]
**1. Summary:**
Problem with posterize levels
**2. Description:**
When choosing a posterize level, you can enter any number and at first that will be applied. However, after that, the level will reset to 16.
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Press Colors -> Posterize;
Input any value > 16;
Click anywhere except to close the posterize window.
**5. Expected result**
Impossible to enter a number > 16 or posterize with a large value will be applied
**6. Actual result**
Posterize level reset to 16
**7. Attachment:**
https://user-images.githubusercontent.com/89531854/139296192-b4f79bbd-cb5f-43f7-92e3-6344ccc1a9d7.mp4

**Comment by circular17** [comment]
fixed on dev. by the way increased max to 32.
