### ISSUE TITLE
Rain settings are not working correctly

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#370]
**1. Summary:**
Rain settings are not working correctly.
**2. Description:**
Setting ''Quantity" does not decrease until the user changes the wind direction.
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Press Render -> Rain
**5. Expected result**
Setting ''Quantity" is reduced in all cases when the user decreases the value with the slider.
**6. Actual result**
Setting ''Quantity" does not decrease until the user changes the wind direction
**7. Attachment:** 
https://user-images.githubusercontent.com/89531854/139296425-b9b544f1-db02-46b7-9e36-78463c48cc15.mov

**Comment by circular17** [comment]
Yes it does decrease, but it takes some time for the droplets to get to the bottom of the screen.
