### ISSUE TITLE
Hotkeys don't work on Russian keyboard layout

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#371]
**1. Summary:**
Hotkeys don't work on Russian keyboard layout
**2. Description:**
Hotkeys don't work on Russian keyboard layout
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Select Russian keyboard layout;
Press any hotkey;
Select English keyboard layout;
Press any hotkey.
**5. Expected result**
Hotkeys work on all language keyboard layout
**6. Actual result**
Hotkeys don't work on Russian keyboard layout

**Comment by circular17** [comment]
duplicate of https://github.com/bgrabitmap/lazpaint/issues/503
