### ISSUE TITLE
Scaling with the mouse wheel centers on the location of the cursor

### ISSUE THREAD

**Issue by AleksandrRybalt** [bgrabitmap/lazpaint#373]
**1. Summary:**
Scaling with the mouse wheel centers on the location of the cursor
**2. Description:**
Scaling with the mouse wheel centers on the location of the cursor. Maybe this is not a bug, but I found it inconvenient.
**3. Environment:** 
Windows 10 Pro Build 19043.1288
LazPaint 7.1.6
**4. Steps to reproduce**
Spin the mouse wheel;
**5. Expected result**
Scaling with the mouse wheel in the center of the image
**6. Actual result**
Scaling with the mouse wheel centers on the location of the cursor
**7. Attachment:** 
https://user-images.githubusercontent.com/89531854/139296741-738d5a5d-8dab-4b8b-b692-d9dfece544e4.mp4

**Comment by circular17** [comment]
Yep, it is done on purpose.

**Comment by circular17** [comment]
You can use +/- keys to zoom from the center.
