### ISSUE TITLE
Error while saving file to the root folder of the disk

### ISSUE THREAD

**Issue by Gos1k** [bgrabitmap/lazpaint#375]
**1) Summary:** Error while saving file to the root folder of the disk

**2) Description**: Error while saving a file to the root folder of the disk, the file can only be saved to subfolders

**3) Environment:** Windows 10 Pro x64, Build 19043.1320, Version  21H1

LazPaint 7.1.6, 64-bit, portable

**4) Steps to reproduce**

Press File
Press Save as 
Select the root directory of the disk
Press save

**5) Expected behavior**
file should be written

**6) Actual behavior**
error at the exit

**7) Attachment:**
![image](https://user-images.githubusercontent.com/93593291/140027875-f640dabe-e5f7-41d7-a6b5-214f71a98e55.png)

**Comment by circular17** [comment]
This may be related to access rights. Do you need elevated privileges to write in the root directory?

**Comment by lainz** [comment]
It's normal, in any lazarus application you can't save a file to C:\

**Comment by circular17** [comment]
Ok thanx
