### ISSUE TITLE
After using the "Past as new image" function, the "Undo" function does not work

### ISSUE THREAD

**Issue by Gos1k** [bgrabitmap/lazpaint#377]
**1) Summary:** After using the "Past as new image" function, the "Undo" function does not work

**2) Description:** After using the "Past as new image" function, the "Undo" function does not work, while after using other insert functions, "Undo"  works correctly

**3) Environment:**

 Windows 10 Pro x64, Build 19043.1320, Version  21H1

LazPaint 7.1.6, 64-bit, portable
 
**4) Steps to reproduce**

Press Edit
Press Past as new image
Press undo

**5) Expected behavior**
The copied image fragment should be pasted, then the result of the paste should be canceled

**6) Actual behavior**
the undo function becomes unavailable

**7) Attachment:**
![image](https://user-images.githubusercontent.com/93593291/140029134-6f6b9ba7-34b1-429b-96ee-8f5a0317a758.png)

**Comment by circular17** [comment]
Indeed. "Paste as new" amounts to creating a new image. As only one image is edited at a time, the previous one is discarded (as if you would do "New image"). A prompt asks for saving the image beforehand.

This may be addressed in the future with multiple documents interface.

**Comment by circular17** [comment]
https://github.com/bgrabitmap/lazpaint/issues/101
