### ISSUE TITLE
Entry bad color values

### ISSUE THREAD

**Issue by AranesT** [bgrabitmap/lazpaint#380]
**1. Summary:**
There is no error window if user enter incorrect color values.

**2. Environment:**
Windows 10 Home 19041.1288
LazPaint 7.1.6 (64-bit)

**3. Steps to reproduce**
 - Click on the color field;
 - Write a color value, that doesn't exist;
 - Tap Enter.

**4. Expected result**
Error window (message), that you have to use existing color values.

**5. Actual result**
 - The previous color value remains;
 - Autocomplete is used.

**6. Attachment:**
![image](https://user-images.githubusercontent.com/90912894/141125522-3e5b62af-fde3-4e87-b8b5-f766c2776784.png)
![image](https://user-images.githubusercontent.com/90912894/141125576-6469f8cf-0d00-4480-94bf-6c9e9bf42e2c.png)

**Comment by circular17** [comment]
fixed on dev
