### ISSUE TITLE
Unable to use tool hotkeys after changing language on PC

### ISSUE THREAD

**Issue by AranesT** [bgrabitmap/lazpaint#381]
**1. Summary:**
Unable to use tool hotkeys after changing language on PC.

**2. Environment:**
Windows 10 Home 19041.1288
LazPaint 7.1.6 (64-bit)

**3. Steps to reproduce**

- Change language on PC (first language is english);
- Try to change a tool using hotkey.

**4. Expected result**
Tool was changed.

**5. Actual result**
Tool wasn't changed.

**Comment by circular17** [comment]
It works when I try it. Do you have any more info on how to reproduce?

**Comment by circular17** [comment]
probable duplicate of https://github.com/bgrabitmap/lazpaint/issues/503
