### ISSUE TITLE
appearing unhandled exception on double click

### ISSUE THREAD

**Issue by Kharkovskiy9** [bgrabitmap/lazpaint#383]
1. Summary:
the appearance of unhandled exception after double-click the okay button in the colorize menu unhandled exception on double click
2. Environment:
Windows 11 Pro
LazPaint 7.1.6 (64-bit)
3. Steps to reproduce:
-open colorize menu
-double-click at okay button

https://user-images.githubusercontent.com/94111460/141345750-6136df49-08b0-4f41-97bc-a08e07460553.mp4

**Comment by circular17** [comment]
fixed on dev branch
