### ISSUE TITLE
Stretching the 'color' menu does not behave smoothly

### ISSUE THREAD

**Issue by Kharkovskiy9** [bgrabitmap/lazpaint#384]
1.Summary:
when working with images of full hd resolution, when stretching the menu for choosing the color of the animation, the animation lags
2.Environment:
Windows 11 Pro
LazPaint 7.1.6 (64-bit)
3.Steps to reproduce:
-open 1920x1080 image
-stretch the color menu

https://user-images.githubusercontent.com/94111460/141454127-1dd7259c-4837-4379-9787-273a3e884c11.mp4

**Comment by circular17** [comment]
this is not handled directly by the program but depends on the update events
