### ISSUE TITLE
It is impossible to delete the selected layer in the Layers window using the Delete key

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#389]
**1.	Summary:** 
It is impossible to delete the selected layer in the Layers window using the Delete key
**2.	Steps to reproduce:**

- Select layer
- Press Delete

**3.	Expected result:**
The selected layer is deleted
**4.	Actual result:**
Nothing happens
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
Using just the Delete key is problematic because there is no "focus" on the layers and Delete is used for other things like selection.

However another shortcut, like Ctrl-Delete could be defined.

**Comment by circular17** [comment]
with #277 you can achieve that by switching to Move Layer tool. then Delete key will delete layer
