### ISSUE TITLE
When using the tool Polyline/Opened curve/Polygon or Polyline/Curve/Select polygon/Select curve, a new point is set when you press Enter

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#390]
**1.	Summary:** 
When using the tool Polyline/Opened curve/Polygon or Polyline/Curve/Select polygon/Select curve, a new point is set when you press Enter
**2.	Steps to reproduce:**

- Select tool Polyline/Opened curve/Polygon or Polyline/Curve/Select polygon/Select curve
- Draw a shape/line
- Press Enter

**3.	Expected result:**
Completion of construction by available points
**4.	Actual result:**
A new point is placed under the mouse cursor. Completion of construction
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
This is the expected behavior. Alternatively you can use right-click for the last point
