### ISSUE TITLE
The main program window becomes inactive when you select Close/Ok/Cancel in the Edit texture window

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#392]
_This is the addition of information to the topic "The program window is minimized to the background" # 356 by AntoninaManzhela_
**1.	Summary:** 
The main program window becomes inactive when you select **Close/Ok/Cancel** in the Edit texture window
**2.	Steps to reproduce:**

- Open the Edit texture window
- Select Close/Ok/Cancel

**3.	Expected result:**
The Edit texture window is closing
**4.	Actual result:**
The Edit texture window is closing. The main program window is shifted one position back relative to other windows.
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Major

**Comment by circular17** [comment]
Fixed by https://github.com/bgrabitmap/lazpaint/issues/417
