### ISSUE TITLE
Twirl in the Filter tab rotates clockwise only

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#397]
**1.	Summary:** 
Twirl in the Filter tab rotates clockwise only
**2.	Steps to reproduce:**

- Select Filter
- Select Twirl
- Select Angle
- Set negative value

**3.	Expected result:**
Image rotates counterclockwise
**4.	Actual result:**
Nothing happens
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
fixed on dev
