### ISSUE TITLE
The list of All supported file types in the Open/Save/Export window opens in a separate window

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#398]
**1.	Summary:** 
The list of All supported file types in the Open/Save/Export window opens in a separate window
**2.	Steps to reproduce:**

- Select File
- Select Open/Save/Save as/Export
- Select the All supported file types
- Open another program from the taskbar

**3.	Expected result:**
The list of All supported file types disappears
**4.	Actual result:**
The list of All supported file types is on top of all windows
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
Yeah, that's a side effect of how the list is shown. Can't really fix it.
