### ISSUE TITLE
miss  lazpaint.zh-CN.po

### ISSUE THREAD

**Issue by kli2013** [bgrabitmap/lazpaint#40]
there is have lclstrconsts.zh_CN.po but not lazpaint.zh-CN.po
can't use zh-cn language
need help

**Comment by circular17** [comment]
Hello. To do the translation we need someone who speaks Chinese and one of the already existing translations (English, Spanish, French or Dutch).

**Comment by circular17** [comment]
Translation done by backdream.
https://forum.lazarus.freepascal.org/index.php/topic,13975.msg351250.html#msg351250
