### ISSUE TITLE
Cannot open a file by specifying the full file name through the Browse Images window

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#400]
**1.	Summary:** 
You cannot open a file by specifying the full file name through the Browse Images window
**2.	Steps to reproduce:**

- Select File
- Select Open
- Specify full filename

**3.	Expected result:**
The program finds the file at the specified path
**4.	Actual result:**
The program does not see the file
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
done on dev
