### ISSUE TITLE
The Space key does not work in move mode if the Text tool is selected

### ISSUE THREAD

**Issue by PakIvan** [bgrabitmap/lazpaint#401]
**1.	Summary:** 
The Space key does not work in move mode if the Text tool is selected
**2.	Steps to reproduce:**

- Select Text
- Press Space key
- Move the image

**3.	Expected result:**
Image moved
**4.	Actual result:**
Travel mode not activated
**5.	Environment:**
Windows 8.1
**6.	Version:**
LazPaint 7.1.6 (64-bit)
**7.	Severity:** 
Minor

**Comment by circular17** [comment]
fixed in dev
