### ISSUE TITLE
The ‘Donate’ button gives a pop-up

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#402]
Priority: MINOR

Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)

Description:
The user presses the ‘Donate’ button and receives a pop-up ‘Donate’ that cannot close.

Steps to reproduce:
1.Click on the ‘Donate’ button on the top panel of the app;
2.‘Donate’ link you to the website https://www.paypal.com/donate/?item_name=Donation+to+LazPaint&cmd=_donations&business=circular%40operamail.com;
3.Close the link;
4.Go to the LazPaint again.

Actual result: The button ‘Donate’ link you to the ’Paypal’ website and when you return to the app you have a pop-up ‘Donate’ on the screen, which disappears only if you close the LazPaint.
Expected result:The button ‘Donate’ link you to the ’Pay

https://user-images.githubusercontent.com/65169031/142728363-e20e01f7-8aa5-431c-83b1-8173d66fcd1a.mov

pal’ website and when you return to the app you don’t have pop-up ‘Donate’ on the screen.

**Comment by circular17** [comment]
I think it is fixed on dev
