### ISSUE TITLE
The ‘Floodfill’ tool does not distinguish between the selected figures and the background.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#403]
Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)

Description:
The user chooses the same colors for the background and the selected figure, after that fill the figure to another color separately from the background is impossible. 

Steps to reproduce:
1.Click on the ‘Floodfill’ tool, choose the color and fill the background of the layer;

https://user-images.githubusercontent.com/65169031/142728409-97cb963f-f013-47b4-a7c5-075a8f2c7076.mov

2.Click on the ‘Edit shape’ tool and make your figure;
3.Click on the ‘Rectangle’ tool and make your figure;
4.Click on the ‘Floodfill’ tool, choose the colors and fill your figures;
5.Fill with same color the background and figures; 
6.Try to fill figures with different color from the background.

Actual result: The ‘Floodfill’ tool changes figures and the background using the chosen color. 
Expected result: The ‘Floodfill’ tool paints figures using the chosen color separately from the background.

**Comment by circular17** [comment]
That's actually the expected behavior when the layer is rasterized. See icon next to the layer in the stack (under the visibility check box).
