### ISSUE TITLE
 Script does not work.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#408]
Priority: MINOR 

Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)

Description:
The user presses ‘Run script’ button or selects a ready-made script in the program and receives an error message ‘Expected Python version 3 but 0 found’.

Steps to reproduce:
1.Click on the button ‘Script’ on the top panel of the app;
2.In the menu that appears, choose the ‘Run script’ button or choose any of the ready-made scripts;
3.Select python project on the device.

Actual result: The script does not open and the application throws an error.

Expected result: The script works correctly.

https://user-images.githubusercontent.com/65169031/142729074-da75efec-f0d6-4241-a060-0bb88d9b49a8.mov

**Comment by circular17** [comment]
There may be two reasons:
- one is a bug when checking the version cause by an error of Python that can be ignored: this is fixed on dev branch
- one is that you don't have Python3 installed. You can download it with the Download button when it complains about not finding Python.
