### ISSUE TITLE
The pop-up window does not adjust to the size of the screen.

### ISSUE THREAD

**Issue by annaasamoylova** [bgrabitmap/lazpaint#409]
Priority: MINOR

Environment: MacOS Big Sur 11.5.1(20G80), LazPaint 7.1.6 (64-bit)

Description:
The user clicks on any button that requires opening a folder on the computer, a pop-up window appears that is not adjusted to the size of the screen.

Steps to reproduce:
1.Click on the button ‘Script’ on the top panel;
2.In the menu that appears, choose the ‘Run script’ button.

Actual result: A pop-up window with an open folder appears, which is incorrectly scaled and does not fit into the screen size.

Expected result: A properly scaled pop-up window appears with the folder open

https://user-images.githubusercontent.com/65169031/142729293-e1516c85-0ca3-476a-9f7f-9f5e91a469fd.mov

**Comment by circular17** [comment]
Indeed. Though I am not sure how to fix this. It depends on the LCL (framework used for windows).

**Comment by circular17** [comment]
Seems it has been fixed in the LCL: https://gitlab.com/freepascal.org/lazarus/lazarus/-/issues/38863
