### ISSUE TITLE
Index out of bounds

### ISSUE THREAD

**Issue by atolstoy** [bgrabitmap/lazpaint#41]
LazPaint 7.0.5 is unable to duplicate a layer. When I press the appropriate button the "Index out of bounds" message pops up.

**Comment by circular17** [comment]
Thanks for the feedback. On which system are you using the software?

**Comment by lainz** [comment]
Confirmed on Windows x64.

**Comment by atolstoy** [comment]
> Thanks for the feedback. On which system are you using the software?

Linux x86_64 (Rosa R11, Alt P8). The issue is reproducible in various distros.

**Comment by circular17** [comment]
Ok I found the bug and fixed it on dev branch. It works on MacOS. Lainz can you check on Windows?

**Comment by lainz** [comment]
The fix works on Windows.

**Comment by circular17** [comment]
And works on MacOS. So that's done.

**Comment by atolstoy** [comment]
Seems that it's not done on Linux x64. 
I followed the outdated compilation instructions in LazPaint Wiki and managed to get the app running in Lazarus, however the Index out of bounds message persists.
Please also provide up-to-date instructions for compiling LazPaint 7.0.x. Thank you.
