### ISSUE TITLE
Translation into Russian in the "File" menu.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#410]
1) Summary:
Translation into Russian in the "File" menu.
2) Description:
When opening the menu in the "File" tab in the Russian version of the application, some item names are not translated into Russian.
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
•	In the program menu, select the "File" tab
5) Expected behavior
All item names are reflected in Russian
6) Actual behavior
Some item names are reflected  in English
7) Attachment:
 ![1](https://user-images.githubusercontent.com/94738204/142757161-58a16cc3-b5fa-4d4a-96a9-be4841309a08.png)
8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
fixed on dev
