### ISSUE TITLE
Translation into Russian in the "File" menu in the "Print ..."

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#411]
1) Summary:
Translation into Russian in the "File" menu in the "Print ..."
2) Description:
When opening the menu in the "File" tab in the "Print ..." item in the Russian version of the application, some labels, buttons and combobox are not translated into Russian.
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
Select the "file" tab in the program menu
Open the item "Print ..."
5) Expected behavior
Everything is reflected in Russian.
6) Actual behavior
Some labels, buttons and combobox are reflected in English.
7) Attachment:
 ![2](https://user-images.githubusercontent.com/94738204/142757220-c7a66a07-0050-40c3-9e47-3cb7b1d4d71c.png)
8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
This is probably translated in next release. Try with latest language files:
https://github.com/bgrabitmap/lazpaint/tree/dev-lazpaint/lazpaint/release/bin/i18n
