### ISSUE TITLE
Incorrect display Button name "Zoom fit"

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#412]
1) Summary:
Incorrect display Button name "Zoom fit"
2) Description:
When opening the menu in the "file" tab in the "Print ..." item in the Russian version of the application, the name of the "Zoom fit" button is displayed incorrectly.
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
- Select the "file" tab in the program menu
- Open the item "Print ..."
5) Expected behavior
The name of the button is displayed in full.
6) Actual behavior
Part of the name is not visible.
7) Attachment:
![3](https://user-images.githubusercontent.com/94738204/142757287-28afa0d0-eb0c-4795-9ed3-50113ce80d36.png)
8) Severity - Minor
9) Priority- Medium

**Comment by circular17** [comment]
fixed on dev
