### ISSUE TITLE
Translation into English in the "file" menu in the "Print ..." item by clicking on the "Configure ..." button

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#413]
1) Summary:
Translation into English in the "file" menu in the "Print ..." item by clicking on the "Configure ..." button
2) Description:
When you open the menu in the "file" tab in the "Print ..." item when you click on the "Configure ..." button in the English version of the program, some labels in the "Configure ..." window are not translated into English.
 3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
Select the "file" tab in the program menu
Open the item "Print ..."
Click on the "Configure ..." button
5) Expected behavior
All labels are reflected in English.
6) Actual behavior
Some labels are reflected in Russian.
7) Attachment:
 ![4](https://user-images.githubusercontent.com/94738204/142757313-9c7c83cd-66d5-4bd3-aa15-221f981b97b0.png)
8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
This dialog box depends on language of the system, so as far as I know it cannot be controlled from LazPaint.
