### ISSUE TITLE
Closing the "File" menu after clicking on the items "Use image browser" and "Remember save format"

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#414]
1) Summary:
Closing the "File" menu after clicking on the items "Use image browser" and "Remember save format"
2) Description:
When you click on the "Use image browser" and "Remember save format" items, the "File" menu closes.
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
- Select the "File" tab in the program menu
- Click on "Use image browser" or "Remember save format"
5) Expected behavior
File menu remains open
6) Actual behavior
The File menu closes
7) Attachment:
https://user-images.githubusercontent.com/94738204/142757375-c50e3672-5054-46d1-843f-744fc30b60ad.mp4
8) Severity - Minor
9) Priority- Medium

**Comment by circular17** [comment]
That's normal behavior
