### ISSUE TITLE
The main window is minimized when the "Edit Selection ..." window is closed.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#417]
1) Summary:
The main window is minimized when the "Edit Selection ..." window is closed.
2) Description:
When you close the "Edit Selection…" window, the main program window is minimized
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
- Select the "Select" tab in the program menu
- Click on the "Edit Selection…" item (the "Edit Selection" window will open)
- Close the "Edit Selection…" window
5) Expected behavior
The "Edit Selection" window closes
The main window remains maximized
6) Actual behavior
The "Edit Selection" window closes
The main window is minimized
7) Attachment:
https://user-images.githubusercontent.com/94738204/142757538-b68b2380-e00a-4b62-93f1-715081d89777.mp4
8) Severity - Major
9) Priority- Medium

**Comment by circular17** [comment]
fixed on dev

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/296
