### ISSUE TITLE
The main window is blocked when the "Edit Selection" window is minimized

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#418]
1) Summary:
The main window is blocked when the "Edit Selection" window is minimized
2) Description:
when the "Edit Selection" window is minimized, this window disappears and blocks the work of the main window.
 3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- Select the "Select" tab in the program menu
- Click on the "Edit Selection…" item (the "Edit Selection" window will open)
- Minimize Edit Selection Window

5) Expected behavior
The "Edit Selection" window is minimized
6) Actual behavior
The "Edit Selection" window disappears
The main window becomes locked
https://user-images.githubusercontent.com/94738204/142758147-17dd8dd7-f4fa-4b81-bca2-a2e8bdc189e2.mp4
https://user-images.githubusercontent.com/94738204/142758148-36dbdd24-0ee3-4b72-a3dd-7c9f524a283d.mp4
8) Severity - Critical
9) Priority- High

**Comment by circular17** [comment]
fixed on dev by preventing minimize
