### ISSUE TITLE
Closing the "View" tab after clicking on some items.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#420]
1) Summary:
Closing the "View" tab after clicking on some items.
2) Description:
When clicking on "Grid", "Toolbox", "Colors", "Palette", "Layers", "Status bar", "Dock toolbox" and "Dock layers and colors" the View tab closes.
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce
- Select the "View" tab in the program menu
- Click on one of the items: "Grid", "Toolbox", "Colors", "Palette", "Layers", "Status bar", "Dock toolbox", "Dock layers and colors".
5) Expected behavior
The View menu remains open
6) Actual behavior
The View menu closes
7) Attachment:

https://user-images.githubusercontent.com/94738204/142758227-d5e0f15c-eee4-48c0-80c3-952d3baa52bd.mp4

8) Severity - Minor
9) Priority- Medium

**Comment by circular17** [comment]
That's the normal behavior.
