### ISSUE TITLE
Translation into Russian in the "Tools" menu.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#423]
1) Summary:
Translation into Russian in the "Tools" menu.
2) Description:
When opening the menu in the "Tools" tab in the Russian version of the application, some item names are not translated into Russian.
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- In the program menu, select the "Tools" tab

5) Expected behavior
All item names are reflected in Russian
6) Actual behavior
Some item names are reflected in English
7) Attachment:
 
![11](https://user-images.githubusercontent.com/94738204/142758331-df29e4f3-3599-4508-96d0-0e5de430d883.png)

8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
This is probably translated in next release. Try with latest language files:
https://github.com/bgrabitmap/lazpaint/tree/dev-lazpaint/lazpaint/release/bin/i18n
