### ISSUE TITLE
Translation into Russian of the "Script" tab.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#426]
1) Summary:
Translation into Russian of the "Script" tab.
2) Description:
The "Script" tab in the Russian version of the application is not translated into Russian.
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- Select the "Script" tab in the program menu

5) Expected behavior
The tab is reflected in Russian.
6) Actual behavior
The tab is reflected in English.
7) Attachment:
 
![14](https://user-images.githubusercontent.com/94738204/142758413-5ddcb3de-62d6-49c5-ba7b-a5e3fbf09a13.png)

8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
This is probably translated in next release. Try with latest language files:
https://github.com/bgrabitmap/lazpaint/tree/dev-lazpaint/lazpaint/release/bin/i18n
