### ISSUE TITLE
Translation into Russian in the "Script"  menu.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#427]
1) Summary:
Translation into Russian in the "Script"  menu.
2) Description:
When opening the menu in the "Script" tab in the Russian version of the application, some item names are not translated into Russian.
3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- In the program menu, select the "Script" tab

5) Expected behavior
All item names are reflected in Russian
6) Actual behavior
All item names are reflected in English
7) Attachment:
 
![15](https://user-images.githubusercontent.com/94738204/142758434-a02ee728-0f93-4a80-a0d3-29f6f3f5c87b.png)

8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
done on dev
