### ISSUE TITLE
Translation of hints with the name of tools into Russian

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#428]
1) Summary:
Translation of hints with the name of tools into Russian
2) Description:
When mouse over the tools in the Russian version of the application, some hints with the name of the tools are not translated
  3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- mouse over one of the tools

5) Expected behavior
All hints with the name of the tools are written in Russian.
6) Actual behavior
Some hints with the name of the tools are written in English.
7) Attachment:
        
![21](https://user-images.githubusercontent.com/94738204/142758509-2766c7cf-7e9a-4634-aa8c-5b038ed0718d.png)
   
                  
8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
This is probably translated in next release. Try with latest language files:
https://github.com/bgrabitmap/lazpaint/tree/dev-lazpaint/lazpaint/release/bin/i18n
