### ISSUE TITLE
Translation into Russian in the file saving window.

### ISSUE THREAD

**Issue by MMendinov** [bgrabitmap/lazpaint#429]
1) Summary:
Translation into Russian in the file saving window.
2) Description:
When you save the file, after choosing the location, name and format of the file, the "Save" window opens, in which labels, checkbox and radio button are not translated into Russian.
 3) Environment:
Windows 10 x64, Build 18362.720, Version 1903
LazPaint 7.1.6, 64-bit
4) Steps to reproduce

- In the program menu, select the "File" tab
- Click on "Save As ..."
- Select the location, name and format of the saved file
- Click the "Save" button (the "Save" window opens)

5) Expected behavior
Everything is reflected in Russian.
6) Actual behavior
Labels, checkbox and radio button are reflected in English.
7) Attachment:
 
![22](https://user-images.githubusercontent.com/94738204/142758535-a239513a-e02f-4b38-b164-7624ae2fb4ad.png)

8) Severity - Trivial
9) Priority- Medium

**Comment by circular17** [comment]
fixed in lastest translation
