### ISSUE TITLE
Command line. Unable to convert file to extension .ico.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#435]
Summary:
Command line. Unable to convert file to extension .ico.
Description:
Command line. Unable to convert file to extension .ico.
Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
Steps to reproduce:
- Launch command line.
- Go to the directory containing the original image (for example photo.jpg).
- Run the command: lazpaint photo.jpg photo.ico
![Новый точечный рисунок](https://user-images.githubusercontent.com/95121493/143727546-22fca78c-8fe4-4b64-9c3e-c33b7ec0080d.png)
Expected behavior:
Image saved successfully as .ico file.
Actual behavior:
Save error.
Attachment:
Image saved successfully as .ico file.
Severity:
Major
Priority:
Medium

**Comment by circular17** [comment]
done with https://github.com/bgrabitmap/lazpaint/issues/438
