### ISSUE TITLE
Command line. Unable to convert file to extension .cur.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#436]
⦁	Summary:
Command line. Unable to convert file to extension .cur.
⦁	Description:
Command line. Unable to convert file to extension .cur.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:

- Launch command line.
- Go to the directory containing the original image (for example photo.jpg).
- Run the command: lazpaint photo.jpg photo.cur

![image](https://user-images.githubusercontent.com/95121493/143727686-45e9e872-7435-4ca3-99db-95729ee9a120.png)

 
⦁	Expected behavior:
Image saved successfully as .cur file.
⦁	Actual behavior:
Save error.
⦁	Attachment:
Image saved successfully as .cur file.
⦁	Severity:
Major
⦁	Priority:
Medium

**Comment by circular17** [comment]
done with https://github.com/bgrabitmap/lazpaint/issues/438
