### ISSUE TITLE
Command line. Unable to create .ico-file.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#437]
⦁	Summary:
Command line. Unable to create .ico-file.
⦁	Description:
Command line. Unable to create .ico-file.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:
⦁	Launch command line.
⦁	Run the command: lazpaint /new(width, height) image.ico
![image](https://user-images.githubusercontent.com/95121493/143727717-efc09048-d07e-4b35-a71b-eb0cbc108e95.png) 
⦁	Expected behavior:
Image created successfully as .ico file.
⦁	Actual behavior:
Save error.
⦁	Attachment:
Image created successfully as .ico file.
⦁	Severity:
Major
⦁	Priority:
Medium

**Comment by circular17** [comment]
done with https://github.com/bgrabitmap/lazpaint/issues/438
