### ISSUE TITLE
Command line. Unable to create .cur-file.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#438]
⦁	Summary:
Command line. Unable to create .cur-file.
⦁	Description:
Command line. Unable to create .cur-file.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:
	Launch command line.
	Run the command: lazpaint /new(width, height) exmp.cur
![image](https://user-images.githubusercontent.com/95121493/143727865-deaeb1b9-0efd-4d59-939d-605c8e4e7736.png)
⦁	Expected behavior:
Image created successfully as .cur file.
⦁	Actual behavior:
Save error.
⦁	Attachment:
Image created successfully as .cur file.
⦁	Severity:
Major
⦁	Priority:
Medium

**Comment by circular17** [comment]
fixed on dev
