### ISSUE TITLE
Translation into Arabic in the "File" menu.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#439]
⦁	Summary:
Translation into Arabic in the "File" menu.
⦁	Description:
When opening the menu in the "File" tab in the Arabic version of the application, some item names are not translated into Arabic.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:
In the program menu, select the "File" tab.
⦁	Expected behavior:
All item names are reflected in Arabic.
⦁	Actual behavior:
Some item names are reflected in English
⦁	Attachment:
![image](https://user-images.githubusercontent.com/95121493/143727952-ff4cbaa3-b1de-4203-9385-541ac2b7d2e0.png)
 
⦁	Severity: 
Trivial
⦁	Priority:  
Medium

**Comment by circular17** [comment]
Redirected to https://github.com/bgrabitmap/lazpaint/issues/441
