### ISSUE TITLE
Translation into Arabic in the "Edit" menu.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#440]
⦁	Summary:
Translation into Arabic in the "Edit" menu.
⦁	Description:
When opening the menu in the "Edit" tab in the Arabic version of the application, some item names are not translated into Arabic.
⦁	Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
⦁	Steps to reproduce:
In the program menu, select the "Edit" tab.
⦁	Expected behavior:
All item names are reflected in Arabic.
⦁	Actual behavior:
Some item names are reflected in English
⦁	Attachment:
 
![image](https://user-images.githubusercontent.com/95121493/143728001-fa85703a-ba64-4d64-bfd2-0872646abc2c.png)

⦁	Severity: 
Trivial
⦁	Priority:  
Medium

**Comment by circular17** [comment]
Redirected to https://github.com/bgrabitmap/lazpaint/issues/441
