### ISSUE TITLE
Unfocus main window.

### ISSUE THREAD

**Issue by Kairest** [bgrabitmap/lazpaint#442]
Summary:
Unfocus main window.
Description:
Loses focus after Edit Selection is closed.
Environment:
Windows 10 x64, Build 19043.1348 Version 21H1
LazPaint 7.1.6, 64-bit
Steps to reproduce:
In the menu open the “Select” tab.
Open the “Edit selection” tab.
Close the “Edit selection” window.
Expected behavior:
After closing the “Edit selection” window, focus on the main window.
Actual behavior:
After closing the “Edit selection” window loses focus.
Attachment:

https://user-images.githubusercontent.com/95121493/143728101-68dee674-fa94-4bf2-a605-6a9d28caf43b.mp4

Severity:
Major
Priority:
High

**Comment by circular17** [comment]
fixed on dev
