### ISSUE TITLE
Original size image stays on background after resampling

### ISSUE THREAD

**Issue by Stompario** [bgrabitmap/lazpaint#443]
Priority: MINOR

Environment: Windows 10 Home 64bit 21H1  19043.1348,  LazPaint 7.1.6 (64-bit) 
Description:

After using the Resample function (CTRL+R) if the original picture was smaller than resampled it stays in the background till user clicked on the workspace or uses some tools, but not all tools or filters affect that frozen image.

Steps to reproduce:
1. Open the image file
2. Run the resample from the Image drop-down menu list or use Ctrl+R hotkey
3. Set the resample size lesser than the original image size. (At least one of the sides must be lesser) and press OK

Expected result: The user sees a new resampled image on the workspace.
Actual result: The user sees a new resampled image placed over the old image on the workspace.

![image](https://user-images.githubusercontent.com/95216029/143856453-c3a49ee8-289a-4008-84b9-16d2e36f5975.png)
![image](https://user-images.githubusercontent.com/95216029/143856542-03ddd74f-eef7-4c59-991a-25b8239c2b06.png)

**Comment by circular17** [comment]
fixed on dev
