### ISSUE TITLE
Blending a window onto the work area

### ISSUE THREAD

**Issue by GHjaz** [bgrabitmap/lazpaint#444]
Priority:  Minor

Environment: Windows 10 (x64), LazPaint 7.1.6 (64-bit)

Description:
Format selection window overlays desktop and other applications

Steps to reproduce:
1. Click on the button ‘File’ on the top panel of the app;
2. In the menu that appears, choose the ‘Open’ button;
3. Click on the droplist 'All supported filetypes';
4. Switch to another app;
Actual result: Overlay a drop list on another window.

Expected result: The format selection window should remain on the layer with the application

https://user-images.githubusercontent.com/43647906/144622622-eb0ac8bb-b07a-4e56-abdd-7cbdc3133718.mp4

**Comment by circular17** [comment]
This is a known bug though not obvious to solve Multiplatform-wise.

**Comment by circular17** [comment]
fixed on dev (Windows-specific)
