### ISSUE TITLE
Zoom fit doesn't make any sense

### ISSUE THREAD

**Issue by Teracle** [bgrabitmap/lazpaint#448]
Priority: Medium

Environment:
Windows 10 Build 19043.1348 Version 1904,
LazPaint 7.1.6 (64-bit)

Description: Zoom fit doesn't fit the picture on the screen

Steps to reproduce:

1. Open LazPaint
2. Open any picture
3. Hold Space, hold left mouse button and move picture to the right
4. Click  **Zoom out** 5 times
5. Click **View** -> **Zoom fit**

Actual result: Image is displayed on right and fits the screen
Expected result: Image is centered and fits the screen

https://user-images.githubusercontent.com/73063742/146010451-7c744992-8ce2-46c2-88ff-90a9ef0e9d05.mp4

**Comment by circular17** [comment]
fixed on dev
