### ISSUE TITLE
No tooltip for layer visibility toggle widget

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#450]
**Severity**
Cosmetic

**Defect descirption**
No mouse hover tooltip is displayed for layer visibility toggle widget

**Steps to reproduce**
- Hover the mouse pointer over any layer's visibility toggle widget
- Wait as long as you wish

**Expected result**
A tooltip appears, with text along the lines of "toggles layer's visibility"

**Actual result**
No tooltip

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

**Additional comments**
Feels bad for a new user to stumble upon a UI element with unkown functionality and no tooltip, not even with the name of the element.

https://user-images.githubusercontent.com/84194921/146569279-4e36580e-b3bc-4188-b011-b1e296dc0b20.mp4

**Comment by circular17** [comment]
okay

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/lazpaint/issues/498

**Comment by circular17** [comment]
Could be implemented in a similar way as the tooltip about the layer type (under the visible checkbox)

**Comment by circular17** [comment]
done by #498
