### ISSUE TITLE
Setting brush opacity to 0 resets the color wheel 

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#451]
**Severity**
Minor

**Defect descirption**
Setting brush opacity to 0 resets the color wheel to display the default color 000000 and alpha channel set to 0

**Steps to reproduce**
- Pick any tool that lets you select color
- Set opacity to 0
- Observe the color wheel

**Expected result**
The color wheel still shows previously selected color

**Actual result**
The color wheel shows 000000 and alpha channel set to 0

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146582098-f94edc22-7e4e-4728-a904-ffc3177dcd4d.mp4

**Comment by circular17** [comment]
Indeed

**Comment by circular17** [comment]
done on dev
