### ISSUE TITLE
'New image' dialogue box doesn't accept decimal comma

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#452]
**Severity**
Minor

**Defect descirption**
'New image' dialogue box fails to interpret comma as the decimal separator

**Steps to reproduce**
- Select **File > New...** 
- Set ratio to any value using decimal comma, e.g. 1,5:1

**Expected result**
The ratio is set correctly both for decimal dot and comma

**Actual result**
Input is ignored

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146583913-e0b7d8a0-128d-44b2-8ee8-9f5b024ac767.mp4

**Comment by circular17** [comment]
In fact this is the expected behavior when the comma is not defined as a separator in the regional settings.
