### ISSUE TITLE
Shape outside of the canvas won't align

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#457]
**Severity**
Minor

**Defect descirption**
Shape off the edge of the canvas is reluctant to align itself as told by **Align shape**

**Steps to reproduce**
- Draw a shape outside the canvas
- Make sure the shape's projections onto the axes don't intersect with those of the canvas
- Select **Edit > Align shape** and click any option therein

**Expected result**
The shape aligns accordingly

**Actual result**
The shape ignores the command

**Additional comments**
The shape will sometimes align if asked super nicely. For example, if the user centers the shape horizontally _and_ vertically, the shape will end up centered

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146640157-66adeee8-cac8-462d-855b-1c37a24c7e57.mp4

**Comment by circular17** [comment]
fixed on dev
