### ISSUE TITLE
Invisible text after 180 plane flip

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#458]
**Severity**
Minor

**Defect descirption**
Text goes invisible if you modify the text box as if to flip it 180 degrees around the vertical axis

**Steps to reproduce**
- Pick **Text** tool and place a text box on the canvas 
- Type anything
- Hold alt and drag the text box's side around, see the video

**Expected result**
The mirrored text is displayed

**Actual result**
The text magically vanishes!

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146640358-0e20e418-dbf9-43b2-a381-30ad5e89ceb1.mp4

**Comment by circular17** [comment]
fixed on dev
