### ISSUE TITLE
Glitchy previews for blend operations

### ISSUE THREAD

**Issue by rj-rl** [bgrabitmap/lazpaint#459]
**Severity**
Minor

**Defect descirption**
Previews for blend operations are displayed incorrectly after using horizontal scroll bar

**Steps to reproduce**
- Open or create a multilayered image 
- Select one of the upper layers and choose **Other...** in the **Blend operation** dropdown menu
- Use any of the horizontal scroll bars in the **Blend operation** widget

**Expected result**
Something scrolls I guess? Not sure what we're supposed to be scrolling tbh, the previews are fit to width anyway

**Actual result**
The little blend operations previews get all messed up

**Environment**
Windows 10, build 19042.1415, version 20H2
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/84194921/146640539-2731b77d-dcec-4d6e-b43c-241696a91a08.mp4

**Comment by circular17** [comment]
Hmm there shouldn't be an horizontal scroll bar. Thanks for reporting it

**Comment by circular17** [comment]
![image](https://user-images.githubusercontent.com/9092455/181878219-58cc6b19-4da1-46fc-9a24-cebc84b13953.png)
fixed on dev
