### ISSUE TITLE
Decrease of the picture quality after saving it as a .jpg

### ISSUE THREAD

**Issue by gwiden** [bgrabitmap/lazpaint#462]
Severity: Trivial

Environment:
Windows 10 Build 19044.1348 Version 21H2,
LazPaint 7.1.6 (64-bit)

Description: while saving a picture as a .jpg with 100% quality, the picture quality is less than 100 %

Steps to reproduce:

1. Open LazPaint
2. Open .jpg picture
3. File - > Save as
4. "Save with specified filename"
5. select 100% quality
6. OK

Expected result
The picture quality will be as close as possible to 100%.

Actual result
The picture quality less than 95%.

![сравнение](https://user-images.githubusercontent.com/49672520/146646017-5792d3d2-e735-4f5e-b8af-59b0154a8fb3.jpg)

[Demonstration ](https://www.youtube.com/watch?v=EThgjL-dgo4)

**Comment by lainz** [comment]
If you save again a jpg file is compressed again and for that you loose
quality I guess.

**Comment by gwiden** [comment]
What is a slider of quality for?

**Comment by lainz** [comment]
Is for setting the quality. But yu say the picture was already a jpg file.
That file is already compressed. If you open and save it again you are
compressing an already compressed file. And jpg is not a loseless format.

**Comment by circular17** [comment]
Not sure this can be improved. There is no such thing as 100% quality with JPEG. If you want to keep quality you need another format like PNG, Webp or LZP.
