### ISSUE TITLE
Deleting after selection changes the active tool to a "Move tool"

### ISSUE THREAD

**Issue by sergvpt** [bgrabitmap/lazpaint#464]
**Severity** Minor

**Description**
Deleting after selection changes the active tool to a "Move tool"

**Steps to reproduce**
1. Choose a select tool
2. Select a part of a pic
3. Press delete button

**Expected result**
"Select tool" is still active

**Actual result**
"Move tool" is active

**Environment:**
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/96376876/146677596-ba592e86-6dd1-4214-8499-f76bd81303fa.mp4

**Comment by circular17** [comment]
fixed on dev
