### ISSUE TITLE
Selection in the "Open" dialog doesn't work correctly with the Shift key

### ISSUE THREAD

**Issue by sergvpt** [bgrabitmap/lazpaint#465]
**Severity** Minor

**Description**
Using the Shift key in "Open" dialog first makes the correct selection, and then, if it's necessary to change selection still selects the first selected file.

**Steps to reproduce**

1. Choose "Open" menu
2. Left-click on any pic
3. Push and hold the Shift key and Left-click on the next pic
4. Stop holding the Shift key
5. Left-click on any pic below the previous two
6. Push and hold the Shift key and push the Down key

**Expected result**
Two files are selected

**Actual result**
Four files are selected

**Environment:**
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/96376876/146681793-37fba764-cbe6-4331-99d7-61c8fd3ffe0b.mp4

**Comment by circular17** [comment]
fixed on dev
