### ISSUE TITLE
A large number of quick commands for one “G” button

### ISSUE THREAD

**Issue by yungmarkusha** [bgrabitmap/lazpaint#467]
Summary:
A large number of quick commands for one “G” button

Description:
Inconveniences when using quick commands. 3 tools are enclosed on one button "G".

STR:
1. Run the program
2. Click "Tool”
3. Look at the "Fill", "Gradient", "Shaded Shape".

The actual result: 
When the “G" button is pressed, 3 devices turn on alternately.

Expected result: 
When the "G" button is pressed, one tool is turned on.

Attachments:
G.PNG

Priority:
Low

Severity:
Minor

Environment:
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

![G](https://user-images.githubusercontent.com/96585839/147402331-e88ceed9-9c11-44bf-af33-01e829c86a57.PNG)

**Comment by circular17** [comment]
Indeed

**Comment by circular17** [comment]
It is not difficult to change the key bindings, though one need to think of all the bindings that might interfere, for example S and X can be used in the curve tool.

**Comment by circular17** [comment]
Related to https://github.com/bgrabitmap/lazpaint/issues/508 (customize key bindings)

**Comment by circular17** [comment]
Here is the current mapping of keys

```
Q      W      E       R     T      Y      U        I       O       P
       magic  eraser        text          rect/    insert  select  drawing
       wand                               ellipse  point   pen     pen

A       S       D      F      G      H      J      K      L
select  curved  poly/         flood  hand   edit          polyline
poly/   vertex  curve         fill/         shape      
curve/                        grad/
auto                          shaded
vertex                        shape

Z       X       C       V       B      N      M
move    swap    color   move/   brush  open   select
vertex  color/  picker  rotate         curve  rect/ellipse
        angle           select
        vertex
```

A and G keys are used more than others. A and X have a conflicting definition.
Clone tool does not have a shortcut.

Unused keys are: Q, R, Y, F, K

New assignments
Y : shaded shapes because next to U (rect/ellipse) and T (text)
K : clone tool because similar sound
F : select rect/ellipse because near D (rect/ellipse)
R : swap color (R like reverse)

Thus the mapping will be:
```
Q      W      E       R     T      Y       U        I       O       P
       magic  eraser  swap  text   shaded  rect/    insert  select  drawing
       wand           color        shape   ellipse  point   pen     pen

A       S       D      F       G      H      J      K      L
auto    curved  poly/  select  flood  hand   edit   clone  polyline
vertex  vertex  curve  poly/   fill/         shape  tool
                       curve   grad/

Z       X       C       V       B      N      M
move    angle   color   select  brush  open   select
vertex  vertex  picker  move/          curve  rect/ellipse
                        rotate
```

**Comment by circular17** [comment]
done on dev
