### ISSUE TITLE
Inconsistency with calling the circle command using the combination “Ellipse"+"Shift”

### ISSUE THREAD

**Issue by yungmarkusha** [bgrabitmap/lazpaint#468]
Summary:
Inconsistency with calling the circle command using the combination “Ellipse"+"Shift”

Description:
When drawing a circle by pressing the combination “Ellipse" +"Shift”, a circle is not obtained.

STR:
1. Run the program
2. Click "Tool”
3. Click "Ellipse”
4. Press and hold the left mouse button
5. Press and hold “Shift”
6. Draw a circle
7. Release "Shift”
8. Release the left mouse button
9. Look on a result.

Actual result:
The shape is an ellipse.

Expected result:
The figure is a circle.

Attachments:
ellipse.mp4

Priority:
Medium

Severity:
Major

Environment:
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/96585839/147402607-d901235b-6c41-41b8-9c0f-165d908bba21.mp4

**Comment by circular17** [comment]
Indeed. Well spotted.

**Comment by circular17** [comment]
fixed on dev
