### ISSUE TITLE
Violation of the boundaries of the spectral palette

### ISSUE THREAD

**Issue by yungmarkusha** [bgrabitmap/lazpaint#469]
Summary:
Violation of the boundaries of the spectral palette

Description:
The color will change if you click outside the palette area, in the area of the square describing this palette.

STR:
1. Run the program
2. Click on the area of the square describing the palette, but not on the palette area.
3. Look at the palette.

Actual result:
The color changes.

Expected result:
The color remains the same.

Attachments:
color.gif

Priority:
Low

Severity:
Minor

Environment:
Windows 10 Build 19043.1415 Version 21H1,
LazPaint 7.1.6 (64-bit)

![color](https://user-images.githubusercontent.com/96585839/147402777-62719012-57cb-4e1d-88c5-495bf69f2a87.gif)

**Comment by circular17** [comment]
Some leeway is intended, though I have reduced it a bit on the dev branch, so that corners of the bounding square won't be clickable
