### ISSUE TITLE
Drop-down menus in the toolbar

### ISSUE THREAD

**Issue by PaulFoxtrot** [bgrabitmap/lazpaint#472]
Sometimes the interface disappears the display of the characters of the drop-down menus in the toolbar
<img width="268" alt="Screenshot 2022-01-19 at 17 58 00" src="https://user-images.githubusercontent.com/26577805/150275630-441d47fc-5755-4624-8c72-83e284c464a0.png">

**Comment by circular17** [comment]
Bug related to the LCL. Maybe there is a trick to avoid this.

**Comment by circular17** [comment]
Seems to be fixed
