### ISSUE TITLE
No text editor margin constraint when moving from one border to another

### ISSUE THREAD

**Issue by GrampusV** [bgrabitmap/lazpaint#474]
**Description:**
No text editor margin constraint when moving from one border to another

**Steps to reproduce:**
1. Select the "text" tool in the toolbar
2. Select an area for writing text (e.g. qwerty) in the workspace
3. Press and hold the left mouse button on one side of the text editor box, and move it outside the opposite side of the text editor

**Actual result:**
When moving one of the faces of the text editor beyond the opposite side, the text disappears.

**Expected result:**
The field of the text editor should be limited, and not allow moving the edges beyond the opposite side

**Environment:**

OS: Windows 10 LTSC  Build 17763.2458 Version 1809
Software: LazPaint 7.1.6 (64-bit)

https://user-images.githubusercontent.com/22413436/150827556-eda62756-4321-4c7a-b604-0143f4ebfec9.mp4

**Comment by circular17** [comment]
related to https://github.com/bgrabitmap/lazpaint/issues/458

**Comment by circular17** [comment]
Moving to the opposite side would flip the text, so it is ok in principle to do that.
