### ISSUE TITLE
Тool hotkeys not working

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#475]
Tool selection hotkeys do not always work. You need to select a tool in the panel.
![Д2_горчие клавишы выбора инструмента не работают](https://user-images.githubusercontent.com/98400320/150983555-dbb5e4a1-91c1-4844-b723-dce47ed322ec.png)

**Comment by circular17** [comment]
probable duplicate of https://github.com/bgrabitmap/lazpaint/issues/475
