### ISSUE TITLE
there is no explanation of the hotkey in the description of the tool in the quickbar

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#476]
there is no explanation of the hotkey in the description of the tool in the quickbar.
![Д3_отсутствие описания горячих клавишь для выбора инструмента](https://user-images.githubusercontent.com/98400320/150985577-9c7a4b35-071f-47a8-a2c1-5d279ce3ae38.png)

**Comment by circular17** [comment]
done on dev
