### ISSUE TITLE
Does not immediately update the color palette after changing the tool

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#478]
The program retains the color palette from the previous tool after selecting a new tool. Тhe palette is updated for the new tool after selecting the provided colors, not in the palette panel

https://user-images.githubusercontent.com/98400320/150991621-4e54b478-d9ec-454e-a5e5-d7cae93aa6fb.MOV

**Comment by circular17** [comment]
The color you change with the color circle is indicated above it. You need to select that you want to change the pen color by clicking on the color preview of the pen in the top toolbar.

If the video, the first color of the background gradient is selected, and that's what's changing.
