### ISSUE TITLE
Тhe selection area cannot be reset with a single press of the ESC key

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#480]
The moment is insignificant, but unpleasant for the user. Тhe selection area cannot be reset with a single press of the ESC key.
![Д4_непросто сбросить выделенную область](https://user-images.githubusercontent.com/98400320/151113280-4671ca3e-d436-4b32-a0f9-f6571aa7cb22.png)

**Comment by circular17** [comment]
On dev branch: when pressing ESC and that the selection layer is empty (nothing was drawn in the selection), then it releases the selection. Otherwise one need either to press Enter to merge it or Delete to remove it.
