### ISSUE TITLE
Buttons are in different languages.

### ISSUE THREAD

**Issue by dev-hl** [bgrabitmap/lazpaint#481]
Description: Buttons are in different languages.

Issue Type: Content

Frequency: Every time

Steps to reproduce:
1. Open "LazPaint" desktop application;
2. Choose the pen;
3. Draw some line on the canvas;
4. Click on Файл(File) - Новый(New);

Expected result: All elements in the window are in the same laguage.

Actual result: There are different languages on the buttons "Yes", "No" and "Отменить".

Environment: Windows 10

https://user-images.githubusercontent.com/98448651/151117672-f150636f-396d-4603-b3a4-ac2a18ec08b1.mp4

![Screenshot_1](https://user-images.githubusercontent.com/98448651/151117680-abd40b6a-2737-4d56-bf68-eff64f0b9f19.png)

**Comment by circular17** [comment]
translated on dev
