### ISSUE TITLE
Incorrect floodfill with low opacity

### ISSUE THREAD

**Issue by dev-hl** [bgrabitmap/lazpaint#483]
Description: Incorrect floodfill with low opacity.

Issue Type: Functional

Frequency: Every time

Steps to reproduce:
1. Open "LazPaint" desktop application;
2. Choose "Simple pen" tool;
3. Decrease opacity to 0.35;
4. Draw some enclosed shape;
5. Choose "Floodfill" tool;
6. Click the point inside enclosed shape.

Actual result: Area inside enclosed shape is filled.

Expected result: Whole canvas is filled.

Environment: Windows 10

https://user-images.githubusercontent.com/98448651/151118698-0ea2b892-538a-4b76-a799-73ee363c8810.mp4

![Screenshot_3](https://user-images.githubusercontent.com/98448651/151118705-b3b47db9-f3a4-4b2f-ba1a-fb9075389cc4.png)

**Comment by circular17** [comment]
That's the expected result. You need to decrease the tolerance (set in the top toolbar) if you would like to stop to smaller color differences.
