### ISSUE TITLE
Unhandled exception while using smooth filter

### ISSUE THREAD

**Issue by dev-hl** [bgrabitmap/lazpaint#484]
Description: Unhandled exception while using smooth filter.

Issue Type: Functional

Frequency: Occasionally

Steps to reproduce:
1.Open "LazPaint" desktop application;
2.Draw some random shape(like ellipse);
3.Click Filter-Smooth.

Expected result: Smooth filter is available for using.

Actual result: Unhandled exception. It's recommended to restart the application. 

Environment: Windows 10

https://user-images.githubusercontent.com/98448651/151119195-8eb5a142-aaf1-432a-9351-c4a7a7247a90.mp4

![Screenshot_4](https://user-images.githubusercontent.com/98448651/151119196-17d2bc9a-487f-4412-b23c-f597c0cb9b62.png)

**Comment by circular17** [comment]
Thank you for reporting this bug.

Ok so the steps to reproduce are:
- draw an ellipse
- click outside of the canvas
- do smooth filter
- try draw a new ellipse

**Comment by circular17** [comment]
fixed on dev
