### ISSUE TITLE
The description of the fill colors does not disappear and possible call the description of the change colors button in one time

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#490]
Description: Drop down menus and description are overlapped

Steps to reproduce:
1.	Open LazPaint
2.	Pick Rectangular
3.	Move cursor to pen color
4.	Move cursor to back color
5.	Move cursor to icon between colors

Expected result: In one time only one menu or description is visible
Actual result: All three windows are visible
![Test](https://user-images.githubusercontent.com/98452721/151147220-eeb8cf22-935c-4399-96f6-9dc852686845.png)

**Comment by circular17** [comment]
This is intended to allow to compare the content.
