### ISSUE TITLE
When deleting a selection, the layer containing the image is deleted

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#491]
When deleting a selection, the layer containing the image is deleted.

![Д10_При удалении выделенного участка удаляется слой на котором содержется изображение](https://user-images.githubusercontent.com/98400320/151147427-07de5515-4a19-49bc-875a-e159f2ef1f45.png)

**Comment by circular17** [comment]
This is the expected behavior. To "delete" just the selection, you can use the "deselect" menu.
