### ISSUE TITLE
Impossible to put the point of the curve in the marker for which the shape is being dragged

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#493]
Description: There is no way to place curve point in small area around red circle in center of printed figure.

Steps to reproduce:
1.	Open LazPaint
2.	Pick Polyline
3.	Place several points
4.	Try to place point near red circle

Expected result: Will be created new curve point.
Actual result: Nothing happens until you select a new location for the point

https://user-images.githubusercontent.com/98452721/151148140-f984374d-46f0-4ed8-8bc0-8d7df71bed04.mp4

**Comment by circular17** [comment]
fixed on dev : using Alt key will hide center point
