### ISSUE TITLE
After canceling the transfer of the selection remain traces of selected area, but there is no it’s color

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#494]
Description: If canceled transfer of area, impossible to see it, because there are only traces of area

Steps to reproduce:
1.	Open LazPaint
2.	Pick Selection pen
3.	Select random area
4.	Use Move Selection
5.	Move area
6.	Press Ctrl + Z

Expected result: Transfer is canceled and selected area at old place
Actual result: Impossible to see selected area, because there is no it’s color, only traces

https://user-images.githubusercontent.com/98452721/151148654-d0b24afa-5baf-4354-b786-2c0b3613747c.mp4

**Comment by circular17** [comment]
That's because the current tool becomes the hand tool, in which the selection is not filled in blue. This becomes blue again if one chooses a selection tool. Though it could be better to keep the current tool.

**Comment by circular17** [comment]
fixed on dev
