### ISSUE TITLE
Error when changing the join type round to miter and vice versa

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#495]
Description: While selected both draw border and fill shape of Rectangular tool, changing join type can cause error

Steps to reproduce:
1.	Open LazPaint
2.	Pick Rectangular
3.	Select draw border and fill shape
4.	Print several figures
5.	Change join type from round to miter or vice versa
6.	Print figure

Expected result: Printed new figure with new join type
Actual result: An error message appears

https://user-images.githubusercontent.com/98452721/151148753-bb8bf4e8-b7d6-4d6d-a723-bd1ab92e747d.mp4

**Comment by circular17** [comment]
fixed on dev
