### ISSUE TITLE
It is possible to make more than a maximum of shapes on one layer

### ISSUE THREAD

**Issue by Badchaos11** [bgrabitmap/lazpaint#496]
Description: For one layer maximum of figures is 24. But if use clone tool, it will be possible to create more than 24 figures.

Steps to reproduce:
1.	Open LazPaint
2.	Pick Rectangular
3.	Create 24 figures
4.	Pick Clone tool
5.	Choose area with shape
6.	Create one shape with this instrument
7.	Pick Rectangular
8.	Create more figures

Expected result: It will be impossible to create new figure
Actual result: You can to create 24 new figures

https://user-images.githubusercontent.com/98452721/151149026-05e1d1ea-65c0-4674-9af1-508af5b1e204.mp4

**Comment by circular17** [comment]
The limit is for vectorial shapes. When using the clone tool, it rasterize the layer. So the previous shapes just becomes like a background picture.
