### ISSUE TITLE
The angle of rotation cannot be changed to the other side

### ISSUE THREAD

**Issue by SieGeR1012** [bgrabitmap/lazpaint#499]
The angle of rotation cannot be changed to the other side.
In the tab "Filter" -> "Rotation"
In the "Rotation" panel, you can change the radius of rotation and its angle. However, the direction of rotation cannot be directed counterclockwise.

![Д13_Угол вращения нельзя изменить в противоположную сторону](https://user-images.githubusercontent.com/98400320/151152947-df3e8c84-b9d4-4c2e-a896-ce025d665e9d.png)

**Comment by circular17** [comment]
Duplicate of https://github.com/bgrabitmap/lazpaint/issues/397
