### ISSUE TITLE
fpc 3.1.1 revision 32333 add declaration  TPointF

### ISSUE THREAD

**Issue by mariuszekpl** [bgrabitmap/lazpaint#5]
It is big problem for var parameters 
TPointF.Round and function round etc...

**Comment by mariuszekpl** [comment]
My changes:
[***** geometrytypes.inc ****]
replace 
  TPointF = packed record x, y: single;
            end;            
  by 
  TPointF = Types.TPointF;


[**** BGRADefaultBitmap.pas ****]
replace round(
by
system.round(

It is all

**Comment by mariuszekpl** [comment]
for TPointF  better is version only for fpc 3.1.1
  {$ifdef VER3_1_1 }
  TPointF = Types.TPointF;
  {$else}
  TPointF = packed record x, y: single;
  end;
  {$endif}

**Comment by circular17** [comment]
fixed in last version of BGRABitmap
