### ISSUE TITLE
Hotkeys don't work on the RUS keyboard layout

### ISSUE THREAD

**Issue by diatarveden** [bgrabitmap/lazpaint#503]
**Description:**

> The tool selection hotkeys don't work, when chosen the Russian language on the keyboard layout

**Step of reproduction:**

> 1. Open LazPaint
> 2. Select Russian keyboard layout
> 3. Press the "J" key

**Expected result:**

> Selected tool is "Edit shape"

**Actual result:**

> Selected tool is "Hand"

**Environment:**

> Windows 10 x64, Build 19042.1586, Version 20H2
> LazPaint 7.1.6, 64-bit

**Severity:**

> Minor

**Priority:**

> Medium

**Attachment:**
![image](https://user-images.githubusercontent.com/102584378/160599310-e0a12e54-d38d-4593-a614-1385975edf35.png)

**Comment by circular17** [comment]
That's surprising.

I suppose that pressing the J key normally puts the Cyrillic letter O (U+041E) or о (U+043E).

The hand tool is the default tool, so I suppose that the key is simply not taken into account.

So I imagine a solution would be to map Cyrillic letters to the corresponding Latin letters when interpreting tool shortcuts.

I've applied this method and seems to solve the issue on MacOS.
