### ISSUE TITLE
Cursor form does not change when use the layer perspective

### ISSUE THREAD

**Issue by diatarveden** [bgrabitmap/lazpaint#505]
**Description:**

> Cursor form does not change from an arrow to a hand when use layer perspective on the layers panel

**Step of reproduction:**

> 1. Open LazPaint
> 2. ''Select Layer'' perspective on the layers panel
> 3. Hover over the circle on the border of the canvas

**Expected result:**

> The mouse cursor will change from an arrow to a hand

**Actual result:**

> Mouse cursor does not change

**Environment:**

> Windows 10 x64, Build 19042.1586, Version 20H2
> LazPaint 7.1.6, 64-bit

**Severity:**

> Trivial

**Priority:**

> Low

**Attachment:**

https://user-images.githubusercontent.com/102584378/160753758-4be48b97-f4b2-41d5-b1cc-666ed8a5479f.mp4

**Comment by circular17** [comment]
fixed on dev
