### ISSUE TITLE
Any knowledge on plugins of this? 

### ISSUE THREAD

**Issue by abdulbadii** [bgrabitmap/lazpaint#532]
Anyone show us some knowledge of this application's plugins ?
is there any, if yes where to ge, how the easiest way to install?
more importantly how could we convert a GIMP plugin can be this application's one?
Thanks before

**Comment by circular17** [comment]
That's a good question. Will ask on the forum.
https://forum.lazarus.freepascal.org/index.php/topic,60822.0.html

**Comment by circular17** [comment]
See https://github.com/bgrabitmap/lazpaint/issues/553
