### ISSUE TITLE
How to slant text and have fixed color background

### ISSUE THREAD

**Issue by abdulbadii** [bgrabitmap/lazpaint#534]
Where is the Lazpaint reference manual site as I need to be able to use it for accomplishing How:

1. To have the text in the layout of other than horizontal which is vertical or being slanted
2. To automatically, ie. the easiest way, have the empty part of canvas (usually, if not always, transparent) to be white when it's included in selection

Thanks much before

**Comment by circular17** [comment]
Hello,

To rotate or slant the text, transform its rectangle as you would do with other shapes:
- By left-clicking and dragging the corners to transform without slant
- By right-clicking and dragging the edges (bottom/top edge to do italic) to do some slant

To have the background as a specific color or image, add a background layer at the bottom of the layer stack. Draw on a layer on top of that: when it becomes transparent, the background layer will be visible.

About having a manual, there is a wiki, but it is not very filled yet.
https://wiki.freepascal.org/LazPaint

Regards
