### ISSUE TITLE
Can not enter a text with '€' symbol

### ISSUE THREAD

**Issue by Lulu04** [bgrabitmap/lazpaint#536]
Hi, first, thanks you for BGRABitmap and LazPaint !
A small bug prevents from entering the symbol of euro € with the Text command and, instead, the export window opens.
My keyboard is AZERTY (french), on Windows 10 64b, Lazpaint 7.1.4 64b

How to reproduce:
  1 - on a new image, click the Text button and draw a rectangular area
  2 - press AltGr+E to print '€' -> this open the export windows

Regard

EDIT: tryed with the last version of Lazpaint 7.2.2 and the problem still exists.

**Comment by fredvs** [comment]
Hello.

_2 - press AltGr+E to print '€' -> this open the export windows_

Hum, strange because the shortcut to export windows is _Ctrl+E_ ( not _AltGr+E_ ).
Tested on Linux and it works as expected. 
I will try asap on Windows 11.

**Comment by Lulu04** [comment]
After some test on Lazarus 2.2.4 Win 64, it appears that a press on AltGr trigger TWO TIME TForm.OnKeyDown event:

  First: with Key = VK_CONTROL, shift = ssCtrl.
 second: with key = VK_MENU, shift = [ssCtrl, ssAlt]
Application.ExtendedKeysSupport := True/False don't change anything.

On my win32 machine, Lazarus 2.2.4, same behaviour: OnKeyDown is triggered two time with same value above.

maybe this is a clue for the solution to this problem.

Regards

**Comment by fredvs** [comment]
Hum, indeed something is strange there.
Notre that I tested Lazarus and in the code-editor AltGr+E gives the €.
So it seems it is not related to LCL ( I did not test yet a simple Lazarus-LCL application, with a TEdit for example, should be interesting to test the result ).

**Comment by circular17** [comment]
This is strange indeed.

A workaround is to hold ALT and type 0128 with the pad. 128 is the value of € in the Windows-1252 codepage.
