### ISSUE TITLE
How to obfuscate (pixelate) a part of a picture

### ISSUE THREAD

**Issue by rchastain** [bgrabitmap/lazpaint#537]
Hello everybody!

Not really an issue but a question. Is it possible in LazPaint to obfuscate a part of an image, by pixelating it?

**Comment by circular17** [comment]
Hello Roland!

Indeed. To do that, select the part you want to obfuscate, then go in Filter > Pixelate and choose the pixel size.

**Comment by rchastain** [comment]
Oh, so simple. I should have thought to that.

Thanks! I close the issue.

**Comment by circular17** [comment]
You're welcome

**Comment by rchastain** [comment]
Here is the result that I get. How to remove the white and black lines?

![2910814a](https://user-images.githubusercontent.com/13957204/221436117-00d09ef6-cab3-4f3f-ab67-f8c998c8a764.jpg)
