### ISSUE TITLE
Some more transformations

### ISSUE THREAD

**Issue by anonimo82** [bgrabitmap/lazpaint#540]
Hello everyone.
I just discovered LazPaint, It's very nice.
But I'm missing some basic stuff, like basic transformations, such as:
- Free rotation (not 90° multiples)
- Skew
- Shear

I hope you'll add them.

Thanks for any help.

**Comment by circular17** [comment]
Hello!

For now, you can do various transformations of layers. In the layer stack, there is a button to do free rotation/zoom and perspective transform. Also if you use the edit shape tool (J), you can transform a raster layer by clicking it and move its axes with the Right mouse button and the Shift key.

Or do you need something else?

Regards

**Comment by anonimo82** [comment]
No, that's exactly what I was looking for.
Thanks a lot.
