### ISSUE TITLE
Linear gradients of SVG

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#56]
[BGRABitmap issue]
From the forum
https://forum.lazarus.freepascal.org/index.php/topic,12037.msg335467.html#msg335467

> Please fix an issue with the linear gradients of svg, which seems to be not painted, but it's only a size issue.
> 
> The issue is in "TSVGElementWithGradient.CreateCanvasLinearGradient(...)" and this code...

```
    p1.x:= Units.ConvertWidth(g.x1,AUnit,w).value;
    p1.y:= Units.ConvertHeight(g.y1,AUnit,h).value;
    p2.x:= Units.ConvertWidth(g.x1,AUnit,w).value;
    p2.y:= Units.ConvertHeight(g.y1,AUnit,h).value;
```

> ...should be...

```
    p1.x:= Units.ConvertWidth(g.x1,AUnit,w).value;
    p1.y:= Units.ConvertHeight(g.y1,AUnit,h).value;
    p2.x:= Units.ConvertWidth(g.x2,AUnit,w).value;  <- change here
    p2.y:= Units.ConvertHeight(g.y2,AUnit,h).value;  <- change here
```

> After these changes the linear gradients will be painted as expected.

**Comment by circular17** [comment]
Ok. Can you do the change on the dev branch?

**Comment by lainz** [comment]
Done.

**Comment by circular17** [comment]
Thanks. I suppose it fixes the problem?

**Comment by lainz** [comment]
I just copied the issue from the forum. I guess that the one posted it tested the solution he provided.

It has sense in the code btw. Point 2 using x2 and y2 instead of x1 and y1.

**Comment by circular17** [comment]
Indeed. I will check when possible

**Comment by circular17** [comment]
Ok it seems to work. :-)
