### ISSUE TITLE
add the option to hide the donation button

### ISSUE THREAD

**Issue by OmlineEditor** [bgrabitmap/lazpaint#575]
please add the option to hide the donation button to the settings.

**Comment by rchastain** [comment]
> please add the option to hide the donation button to the settings.

If you make a big donation, we will maybe add that option.

**Comment by circular17** [comment]
Hello @OmlineEditor,

We understand that users have diverse preferences when it comes to the user interface, and we always strive to accommodate those as much as possible.

Currently, the donation button is designed to be minimally intrusive, appearing only when no tool is selected. This approach helps keep LazPaint free for everyone while also supporting the project's development.

As @rchastain alluded to, we're not in a position where we're receiving a large volume of donations that would justify tackling this particular request at the moment. However, we're open to revisiting this discussion in the future should circumstances change.

Regards

**Comment by c-sanchez** [comment]
I don't find the button really annoying, it is very small and in a good place in my opinion.

In fact, in such a case, the ideal would be to make a special version of LazPaint for donors.
With some special features and .... the hidden button? 😂

**Comment by OmlineEditor** [comment]
you can also make it possible to hide the button if you have made a donation, for example, entered a code to hide the button

**Comment by fredvs** [comment]
> you can also make it possible to hide the button if you have made a donation, for example, entered a code to hide the button

And what if people want to make a second (or multiple) donation(s)? 
 ;-)

**Comment by circular17** [comment]
Now I am thinking of making that button fullscreen when no image is loaded.
