### ISSUE TITLE
Feature request: Resize canvas when pasting a big image

### ISSUE THREAD

**Issue by FrostShock** [bgrabitmap/lazpaint#577]
Hello, I would like to place a feature request:

My canvas size is 10 x 10 pixels
Then I paste a big image (800 x 1000 pixels). In other painting pograms, the canvas is automatically resized to the size of the image I am pasting. At very least, LazPaint should ask me if I want to resize the canvas to match the size of the image that I am pasting from the clipboard

Please consider about adding this feature.
Thank you

**Comment by circular17** [comment]
Sure!

**Comment by circular17** [comment]
Related to #339

**Comment by circular17** [comment]
done on dev branch
