### ISSUE TITLE
Bug "Too many shapes in layer" after few text entries V 7.2.2  64bit on Linux MX

### ISSUE THREAD

**Issue by Sototoki** [bgrabitmap/lazpaint#578]
Message: 
"Too many shapes in layer" after few text entries 
(LazPaint V 7.2.2  64bit on Linux MX-21.3_ahs_x64, will be the same on other MX )

Action to achieve:
-open .jpg-  picture ( about 1 MB)
-select text tool with mouse click
-A: place with mouse click cursor in pic, type two hyphen on keyboard
-repeat A:   maybe roundabout 9 times then message appears, no further 
  entry possible, app has to be closed and reopened;

if this is really necessary out of whatever reasons, 9 times are much much much to less.
Never seen this on another paint program

**Comment by circular17** [comment]
Hi Sototoki,

Thank you for popping by. Indeed, the limitation is too low. I intent to push the limits in the next version.

Note that you don't need to close the application. You can add a new layer.

Regards

**Comment by circular17** [comment]
fixed in dev
