### ISSUE TITLE
LazPaint 7.2.2.  try to open avif results in acess violation when trying to open from Thunar on Linux MX

### ISSUE THREAD

**Issue by Sototoki** [bgrabitmap/lazpaint#585]
When trying to open a pic in avif format in Thunar with "open with"Lazarus, it results in an AV.
When trying to open with the open dialog, no preview, no opening possible.

Because avif seems to be a more and more used format (e.g. etsy) maybe this would be worth
having it working

Thanks in advanvce and for the good work!

System:
Kernel: 6.3.0-2mx-ahs-amd64 [6.3.11-1~mx21ahs] x86_64 bits: 64 compiler: gcc v: 10.2.1 
           parameters: BOOT_IMAGE=/boot/vmlinuz-6.3.0-2mx-ahs-amd64 root=UUID=<filter> ro quiet 
           splash 
           Desktop: Xfce 4.18.1 tk: Gtk 3.24.24 info: xfce4-panel wm: xfwm 4.18.0 vt: 7 
           dm: LightDM 1.26.0 Distro: MX-21.3_ahs_x64

**Comment by circular17** [comment]
Hi Sototoki,

Thanks for popping by. It is likely the error is related to a newer version of AVIF. It may be fixed in the dev branch. So this is likely to work in the next release. However for good measure, can you give me the libavif version, to do a more thorough check?

Warm regards.

**Comment by circular17** [comment]
Looking at repology, I found that MX Linux uses version 1.0.4. I have done a test with this version (with brew on MacOS) and it seems to work. So I'll assume this request is done.
