### ISSUE TITLE
dock layer stack or colors to main window

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#64]

**Comment by lainz** [comment]
This will be really nice, specially for those who are not used to floating windows like is done in Lazarus.

I think that can be done moving everything outside the form, say into a panel, put them into the main window and use splitters to arrange them. One splitter between the layers and colors to resize vertically, and a second one to resize horizontally, to set the width of that. I'm not sure what will happen to the left toolbar when moved to the right, if it will be at the left of those panels, or at the right side.

**Comment by c-sanchez** [comment]
LazPaint: https://i.ibb.co/wpCvnvj/lazpaint.png
Phoxo: https://i.ibb.co/1m6gg3k/phoxo.png
PictBear: https://i.ibb.co/tM8byr9/pictbear.png
Yeah, worrying about where put the color and layers window is not very nice, "I want just edit my image" :P

**Comment by circular17** [comment]
Agreed

**Comment by circular17** [comment]
done on dev branch
