### ISSUE TITLE
group items in toolbar

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#67]
Grouping items of the toolbar to save space on the docked toolbar.

**Comment by c-sanchez** [comment]
We can see is in some editors
Photo Pos Pro 3
https://i.ibb.co/7YNwJyy/sshot-003.png
https://i.ibb.co/yk4WFQ0/sshot-002.png

LazPaint docked toolbox
https://i.ibb.co/R96WSmc/toolbox.png

LazPaint docked toolbox with grouped items example
https://i.ibb.co/vHx9z16/toolbox-group.png

**Comment by circular17** [comment]
done on dev branch
