### ISSUE TITLE
linux64

### ISSUE THREAD

**Issue by JonnyTech** [bgrabitmap/lazpaint#7]
In releases there is a linux32 build - any possibility of a linux64 one?

**Comment by lainz** [comment]
Hi, BTW there is a way to compile both 32 and 64 bits under linux with a single installation of lazarus?

Under Windows there are 2 build modes in LazPaint, one for win32 and one for win64, and I need only a single IDE to compile both thanks to the add-ons, 32 bit IDE with 32 & 64 bit compile or 64 bit ide with 64 & 32 bit compile.

**Comment by lainz** [comment]
Sorry for the delay, there is a linux64 deb package available now. Is for amd64, tested under Ubuntu.
