### ISSUE TITLE
scripting language

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#70]
Pascal or Python

**Comment by lainz** [comment]
Python, really is the most used language for enthusiasts. Blender uses Python. In the other hand, there is also a JavaScript engine for Lazarus that can be used too. If I remember correctly Photoshop uses a kind of JavaScript (also VBScript and AppleScript, seen in his website).

**Comment by circular17** [comment]
I would like to do Python as well. I don’t know yet how to interface it with the application

**Comment by lainz** [comment]
https://github.com/Alexey-T/Python-for-Lazarus
https://wiki.lazarus.freepascal.org/Using_Python_in_Lazarus_on_Windows/Linux

**Comment by lainz** [comment]
Maybe we can ask to the maintainer for help.

**Comment by circular17** [comment]
Looks promising

**Comment by circular17** [comment]
Also it would be great to record scripts like a macro

**Comment by circular17** [comment]
I looked at Alexey package. To make it work I had to find the exacty library name (.so). That would be ok for a personal program but not for a public one. Maybe there is something I am missing.

Otherwise I am thinking that it would be possible to interact with the script using standard input/output of the console.

**Comment by lainz** [comment]
Hi, ok. Yes a command line can be good. An interface that builds the output can be made, then you can parse the commands in LazPaint.

Like:

sendcommand('newdocument', 800, 600)
sendcommand('drawpixel', 10, 10, BGRA(100,100,100,255))
sendcommand('execute')

or

LazPaint.newdocument(800, 600)
LazPaint.drawpixel(...)
LazPaint.execute()

When calling execute the strings are sent to output.

**Comment by circular17** [comment]
I've started implementing it on dev branch and it works. For now, I've just added a menu File > Run script and a few script examples in lazpaintscript folder.

It interact with Python using standard input/output/error. It has medium speed, which is enough for scripting.

**Comment by lainz** [comment]
I've tested it and it works on Windows. Unfortunately I can not build my owns scripts for now, since I've not used python too much yet.

**Comment by circular17** [comment]
Thanks for testing.

Well there just a few commands yet, so you would not go very far. Python is in fact relatively simple, I am sure you will understand most of it by looking at examples.

**Comment by c-sanchez** [comment]
Umm, I guess is a bit later to change the scripting languague, I would like think is not, but, why not Lua?
IMHO I think Python have more cons which pros

1. Maybe is not so popular as Python, however Lua remains very popular.

2. Lua it's very lightweight, runs in older systems, like Windows XP.
On the other hand Python requires to have Python installed in the system, I know this can be "embedded" somehow
but I think sincerely it will end up inflating the program, One of the reasons lazpaint is great is that it's light and fast.

3. Python 2? Python 3?

Anyway beyond just my opinion, we can see a comparison :)
https://stackshare.io/stackups/lua-vs-python
Lua: Fast learning curve, Very easy to embed in C programs, Efficient memory usage, Open Source, Good for game scripting.
Python: Great libraries (We don't need that here), Readable code (ok), Beautiful code (huh ok?), Rapid development (...), Large community
Still divided between python 2 and python 3, Poor syntax for anonymous functions (hah! beautiful code?), Package management is a mess, GIL, Performance impact.

The programs I found light and fast + integrated scripting don't uses really Python

Maybe even Javascript? by example in AkelPad we can use Javascript or VBScript, and this is very very lightweight and have a bunch of script extending the program features :P

And finally, check this https://en.wikipedia.org/wiki/List_of_applications_using_Lua
The most notable and related here:
**Adobe Photoshop Lightroom** uses Lua for its user interface
**Artweaver graphics editor** uses Lua for **scripting** filters.
The **darktable** open-source photography workflow application is **scriptable** with Lua
GrafX2, a pixel-art editor, can run **Lua scripts** for simple picture processing or generative illustration.
**Moho**, an animation software package distributed by Smith Micro Software, uses **Lua as its scripting** language, and all of its native tools are built as editable scripts.

**Comment by circular17** [comment]
Indeed I already started coding it. Nevertheless I had a look at lua. I find it ok though not as beautiful as a programming language and it is less popular. 

Regarding speed it may not be so important because scripts are mainly used to call functions. There may be some cases though where it could matter. For example when programming a filter at a pixel level.

Regarding installation, on Linux it is already installed. On Windows that’s indeed an additional installation though maybe we could supply Python dll. I suppose that would be the same with lua.

**Comment by lainz** [comment]
Lua was my first language, using Autoplay Media Studio, so I did this https://github.com/lainz/lainzcodestudio, that is an example on how lua can be embedded.

An example script
https://github.com/lainz/lainzcodestudio/blob/master/scripts/7zip.lua

A library of functions I did based on Autoplay Media Studio ones
https://github.com/lainz/lainzcodestudio/wiki

So I think is good too. I also agree on JavaScript too, it can be embedded into a Pascal application without third party installs.

I'm new to python and I already created 3 scripts and was not such that different from other languages, so it was OK too.

**Comment by lainz** [comment]
Something that bothered me when using Lua was this ~=, is not easy to write in a spanish keyboard, it requires a combination of keys to put that symbol...

**Comment by c-sanchez** [comment]
> Indeed I already started coding it. Nevertheless I had a look at lua. I find it ok though not as beautiful as a programming language and it is less popular.

That's why I said Lua is still very popular, maybe not as python, but that difference is really not very important here
Both are are very very popular scripting languagues

> Regarding speed it may not be so important because scripts are mainly used to call functions. There may be some cases though where it could matter. For example when programming a filter at a pixel level.

You have said, it could be important in certain cases, why ignore that odds? :P

> Regarding installation, on Linux it is already installed. On Windows that’s indeed an additional installation though maybe we could supply Python dll. I suppose that would be the same with lua.

With lua it'll probably be smaller, faster, (harder better faster stronger? ;P )
And well using Python, will these scripts work on Windows XP for example?
I still think Python has more disadvantages than advantages.

> Lua was my first language, using Autoplay Media Studio, so I did this https://github.com/lainz/lainzcodestudio, that is an example on how lua can be embedded.

good, the lua53.dll is just 253kb :)

> Something that bothered me when using Lua was this ~=, is not easy to write in a spanish keyboard, it requires a combination of keys to put that symbol...

haha I don't understand that, ie in Python and any other language we need use = (**shift** + **0**) ! (**shift** + **1**) ~ (**alt** + **+**) and any key conbination, no?

**Comment by c-sanchez** [comment]
About that "beauty code" with python, that's debatable I would like leave this refference:
* A pretty-printer exists for Lua, so code could be "standardized" just as easily as for Python. -SharkD
* Yeah, but you're not forced to use it. Python forces your code to look at least half-way decent. Big difference. —MR

Link: http://lua-users.org/wiki/LuaVersusPython

Maybe you can make a quick Lua implementation to compare?
I guess lainz is the most is best suited to give an "impartial" opinion about both :P

**Comment by circular17** [comment]
Well I think it matters that the language would be used if we want people to write scripts. But of course that’s not a definitive point.

About Python 2 and 3 basically now Python 3 is always available and is now recommended over 2.

Lua doesn’t seem to have a native GUI where Python has tkinter. It is very convenient to have that to make plugins.

For Windows XP and earlier, thanks for pointing out that latest version of Python is not supported. Only up to version 3.4.2. That may be a drawback though if any version 3 is ok I suppose. 

Object oriented of Python is a great feature to do GUI it have special objects like pixel values.

So well I am not so convinced about Lua. Though that’s an interesting debate.

**Comment by lainz** [comment]
I'm not sure if with lua you can do the same as python. Maybe c-sanches can try, for example recreating the api that currently uses with python lazpaint but in lua to see if is possible to use it.

**Comment by c-sanchez** [comment]
Heh nope, unafornatelly I have not much programming skills :(
So I'm commenting more like a enthusiast heh :P

**Comment by c-sanchez** [comment]
Heh nope, unafornatelly I have not much programming skills :(
So I'm commenting more like a enthusiast heh :P

**Comment by lainz** [comment]
Ok I understand.

Well I'm not sure if this is possible, but my idea was to use the same commands lazpaint does with python, but using Lua. At the end everything is a text sent to lazpaint.

So we can reuse lazpaint code that works with python with lua or any other scripting language. And circular don't need to recreate everything again. And we can add as many languages we want.

Need to find time to test that, maybe using a lua binary instead of a dll.

**Comment by c-sanchez** [comment]
Oh, that sound really good, allowing use Python, Lua, Javascript, or any language is much better :)

**Comment by lainz** [comment]
Well, I've checked the python sources, and seems that what I though is not possible in a simple way.
For example this line:
`ast.literal_eval`
Eval is usually mean to "compile and run" a script. So it's input must be a python script, and I can not evaluate that in Lua without changing LazPaint sourcecode.

**Comment by circular17** [comment]
This literal_eval function is not really evaluating a script. It is more like evaluating a string to a value : integer, string, list of integers, etc.

The return value of the functions called by the script is basically provided as a string following Python conventions:
* 34.8
* 'Hello\nworld'
* [2, 3, 4]
* (12, 23)
* True

Similarly, parameters provided to functions are provided by the script as a dictionary following Python convention, for example:
* {'Index': 2}
* {'Options': ['Option1', 'Option2'], 'Coord': (12, 23)}

**Comment by lainz** [comment]
Ok, I see. Yes Lua was made to generate dynamic configuration files, or script simple game logic.
Better stick to python that has more features, I think.

**Comment by circular17** [comment]
Ok.

**Comment by circular17** [comment]
Basic Python script support done on dev branch.
