### ISSUE TITLE
Handle Retina display 

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/lazpaint#82]
Bitmap need to be twice as big with Retina display

**Comment by lainz** [comment]
Hi, I asked @esvignolo and he can help you with the testing of retina display.

I know that retina display is already available on image components like TImageList, so you can ask the developers (I tried but I get no help from them in the bugtracker) of that component, or just look at the source code of the MacOS implementation of TImageList.

**Comment by lainz** [comment]
I recommend you to install trunk of lazarus to get the latest sources of TImageList.

**Comment by circular17** [comment]
Ok I take a note about TImageList for a start

**Comment by circular17** [comment]
Done for color chooser on dev branch

**Comment by circular17** [comment]
Done for image view

**Comment by circular17** [comment]
done
