### ISSUE TITLE
Can't run LazPaint on Ubuntu 19.10

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#92]
> '/home/lainz/Descargas/lazpaint7.0.7_linux64_no_install/lazpaint64/lazpaint' 
> /home/lainz/Descargas/lazpaint7.0.7_linux64_no_install/lazpaint64/lazpaint: error while loading shared libraries: libgdk-x11-2.0.so.0: cannot open shared object file: No such file or directory

**Comment by lainz** [comment]
Using

> apt-get install libgtk2.0-0

Now I can run LazPaint, but it crashes.

**Comment by circular17** [comment]
Hmmm is it 64 bit Linux? What do you get with “uname -m” ?

**Comment by lainz** [comment]
> uname -m
> x86_64

What happens is that I can run it, it shows the window, but for example trying to close the window or resize the window causes that the application freezes. Resizing seems to have problems, since the controls inside remains of the original width and height.

**Comment by lainz** [comment]
![Captura de pantalla de 2019-10-30 11-05-56](https://user-images.githubusercontent.com/4131395/67865083-7c47cf80-fb05-11e9-9589-20c948396e3a.png)

**Comment by lainz** [comment]
Seems that Lazarus is freezing too
https://forum.lazarus.freepascal.org/index.php/topic,47240.0.html

**Comment by circular17** [comment]
Hmmm it would be related to Lazarus 2.0.4 maybe?

I am on Linux Mint 19.1 Tessa and Lazarus 2.0.2 and not having this problem.

**Comment by lainz** [comment]
Well this is another distro, so something that diferentiate them must be. I not tested Lazarus, just did a quick search in the forum. What I just tested is LazPaint, the binary you created, it was made with 2.0.2? Well that is the thing is failing, but maybe is an event or something in this version of Ubuntu, a bug in Ubuntu and not in LazPaint?

Well also I must say I'm running in a VM, but tested other programs and works fine, not Lazarus programs btw.

**Comment by lainz** [comment]
I can't find a way to change the window manager from a setting.

I seen running lazpaint from the command line
Failed to load module "canberra-gtk-module"

Then I installed
sudo apt install libcanberra-gtk-module libcanberra-gtk3-module

LazPaint freezed at the beginning, but then a popup of the system come saying "lazpaint is ready".

Then from now when I run LazPaint it says 'lazpaint is not responding' but if I wait a few seconds, then it becomes responsive and I can use it.

**Comment by lainz** [comment]
In the forum they say that changing the UI manager works, so is a problem with lazarus and the gnome desktop used in that release. I close this because we can do nothing to fix it, is a lazarus problem or a gnome problem with gtk2 apps, for something gtk2 doesn't come preinstalled in the latest ubuntu.

**Comment by neurolabusc** [comment]
See these [solutions](https://askubuntu.com/questions/1187246/ubuntu-19-10-crash-when-lazarus-runs/1193259)

1. (Temporary, probably a bad idea) launch as super-user: `sudo ./project1`
2. (Temporary) launch with `dbus-launch --exit-with-session ./project1`
3. (Permanent) Run `sudo apt-get install appmenu-gtk2-module` and restart your computer. 

This impacts some GTK2 applications including those built with Lazarus and others (e.g. HexChat) but not all. So it is not only a Lazarus problem. If anyone has any ideas about how Lazarus applications can be updated to avoid this (or have their requirements updated so users are told they need to install appmenu), I would be happy to hear about it.
