### ISSUE TITLE
Can't load SVG into LazPaint

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/lazpaint#95]
Hi, I can't load this SVG file into LazPaint, maybe because it has CSS inside?
[flores.zip](https://github.com/bgrabitmap/lazpaint/files/3802465/flores.zip)

**Comment by lainz** [comment]
Hi again, seems that is not related with the CSS properties, here is the same image without CSS.
[flores_nocss.zip](https://github.com/bgrabitmap/lazpaint/files/3802468/flores_nocss.zip)

**Comment by circular17** [comment]
Hi

What is the error ?

**Comment by lainz** [comment]
TBGRAWinBitmap.ReallocBitmap: Windows Error 87

**Comment by lainz** [comment]
I found a solution, it does not works when using the lazpaint "image explorer" that has at the right the full view of the image.

But if I change to thumbnails "big icons", it works and I can open the image.

**Comment by circular17** [comment]
Hmmm, could be related to its size then

**Comment by lainz** [comment]
Yes, its an A4 page, with 300 dpi.

**Comment by circular17** [comment]
Ok. Fixed on dev branches of bgrabitmap and lazpaint
