### ISSUE TITLE
Text tool - pressing enter moves cursor 2 lines down 

### ISSUE THREAD

**Issue by johnfoxii** [bgrabitmap/lazpaint#99]
Pressing enter move cursor 2 lines down as if it were treated as a paragraph. The only way to place text onto the next line is to fill the rest of the current line with spaces until it wraps.

**Comment by circular17** [comment]
Indeed. Enter makes a new paragraph, which has a vertical margin of half a line. You can insert a line break using Shift-Enter. This way you won't have the margin.
